### ISSUE TITLE
Вложенные логи

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#102]
Логгирование вложенных функций продолжает происходить.
В результате на тесте
```
N1 = Glushkov ((ab)*|a)* !!
N2 = Glushkov (a|(ab)*)*
N3 = Annote.Determinize N1
Equal N1 N2
Test ab(ab|a)*ababa ((ab)*a)* 1
SemDet N1
SemDet N2
```
порождается 117 страниц логов, со сплошными вызовами `Subset` и `Arden`. Похожая проблема есть и в других тестах.

**Comment by xendalm** [comment]
У некоторый функций преобразователя до сих пор нет своих логов, поэтому вызываются вложенные. Надо доделать
