### ISSUE TITLE
Arden bugs

### ISSUE THREAD

**Issue by mathhyyn** [StarikTenger/Chipollino#106]
Заметила, что Арден валится на языках, заканчивающихся не на *

```
Regex r;
r.from_string("(ab)*a*");
FiniteAutomaton a = r.to_glushkov();
cout << a.nfa_to_regex().to_txt() + "\n";
```

по автомату (Глушков)
![output1](https://user-images.githubusercontent.com/79749959/200190829-2b22cfa5-dde8-4c85-9139-1bfe2f562cb0.png)
строится что-то явно лишнее
`|a(ba)*b|(aa*)*(a(ba)*baa*)*`

на автомате (Томпсон)
![output1 (2)](https://user-images.githubusercontent.com/79749959/200191543-6c05ed3c-4771-4d67-bc6d-efc83fc14b48.png)

отказывается работать _(и я вместе с ним)_

**Comment by TonitaN** [comment]
Пока не исправится Арден, не удастся разбираться с `SemDet`

**Comment by TonitaN** [comment]
Ещё один пример падения `Arden` (запускала из `Example.cpp`):
```
       	string regl = "(ab)*a";
	Regex r;
	if (!r.from_string(regl)) {
		cout << "ERROR\n";
		return;
	}
	a = r.to_glushkov();
	d = a.annote();
        cout << d.nfa_to_regex().to_txt();
```
Из-за чего моя попытка исправить реализацию семантического детерминизма с той, которая была в ТЗ (и годилась только для семантически детерминированных НКА 🤡) на нормальную тоже не удаётся: в той ардену приходится работать с размеченными регексами.
Надеюсь, когда будет нормальный `Arden`, я смогу внести правки в `SemDet` (сама накосячила - самой и исправлять) и всё будет ок.
