### ISSUE TITLE
Как читать результат Ambiguity?

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#109]
Судя по тому, что на результатах детерминизации возвращается 2, 2 - это однозначно. 
Но у меня удалось получить только значения 2 и 3, даже в автомате Томпсона таких диких регулярок, как `(((a)*)*)*`, где есть бесконечный цикл по эпсилон-переходам, всё равно тройка.

**Comment by xendalm** [comment]
Уже нашел сегодня проблему с переполнением, когда слишком быстро растет количество путей, поэтому выдает, что полиномиально, пока думаю как решать. Результат буквами в логах(

**Comment by TonitaN** [comment]
А если логи пока кривые? Из `Example.cpp` всё запускаю, по понятным причинам.

**Comment by xendalm** [comment]
Я понимаю( Экспоненциально, однозначно, почти однозначно, полиномиально (0,1,2,3)

**Comment by TonitaN** [comment]
Пока изменения не в ветке `main`, я их проверять через голову капитана не стану :(

**Comment by TonitaN** [comment]
Глушковский автомат по `(ab|ab)*` определяется как полиномиально неоднозначный. Но можно посчитать по росту числа слов чётной длины относительно длины путей в автомате: слова вида `(ab)*` имеют 2^n разных разборов. Причём на регулярке `(a|a)*` всё считается правильно.
Вероятно, вы захотите меня убить, но я только что нашла в статье простой критерий экспоненциальной неоднозначности автомата, не требующий никаких `LongDouble` 👽 Только я вам его не скажу, а то начнёте ещё переделывать, а ведь ваша реализация открывает возможности более подробного комбинаторного анализа автоматов, (простая - нет). Вам за труды +3 балла дам, когда поправите баг с `(ab|ab)*`.
