### ISSUE TITLE
Усиление функциональности

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#111]
Мне написали несколько участников проекта, что они будут продолжать его в рамках третьей лабораторной. Но возникает проблема с коллективной работой: если продолжающий один, то координация не актуальна, а для четырёх уже точно понадобится. Поэтому сдвигаю срок выдачи лабы на 12 ноября, после того как закроем 2 лабораторную. Теоретические материалы я всем записавшимся раздам заранее, но коммитить пока ничего не надо.

**Comment by StarikTenger** [comment]
Вся команда, за исключением @SoFa325, готова продолжить работу в рамках 3й лабораторной

**Comment by TonitaN** [comment]
Варианты доработки, которые я могу предложить на выбор (включая те, что в слайдах):
- [ ] 1-однозначность языка по Брюггеманн-Вуду (бонусом - и извлечение 1-однозначной регулярки)
- [ ] префиксная грамматика по НКА (и наоборот - бонусом)
- [ ] тест минимальности НКА по Глейстеру-Шаллиту
- [ ] встраивание оператора `^` (+ РЕФАКТОРИНГ у всех)
- [ ] документация
- [ ] документация (ещё одна)
- [ ] REPL + алгебра автоматов (не языков - т.к. в текущей реализации это именно алгебра языков)
- [ ] реализация оптимальных алгоритмов минимизации (задача тесно связана с документацией - они должны быть различимы по логам)
- [ ] (кто скучает без алгебры, как Матвеев) определения беззвёздности языка по теореме Шутценберже (определяем апериодичность синтаксического моноида 💖- дружеский вариант к варианту 4)
- [ ] переход к регуляркам над интервалами от регулярок над буквами (т.е. допускается писать вместо буквы интервал или перечисление - здесь тоже РЕФАКТОРИНГ, потому что переводить интервалы типа [A-z] в >50 альтернатив неразумно, и надо менять структуру данных, чтобы хранила непересекающиеся подмножества букв как элементы алфавита ☠). 

Если кто-то чувствует такое родство с проектом, что имеет свои мысли по его развитию, - предлагайте. Возможно, вы сами сможете поставить себе задачу на 3 лабораторную.

**Comment by TonitaN** [comment]
Вообще, проект можно развивать в двух направлениях:
- вглубь в теорию автоматов (с охватом всего известного и малоизвестного, но полезного - так он станет более уникальным, но более узко специализированным)
- вширь в теорию формальных языков (так он может найти большую аудиторию, т.к. КС-грамматики и PDA нужны всем, и все хотят наглядных объяснений, но чтобы развить уникальность, придётся довольно много вкладывать сил)
Мне в чём-то импонируют оба подхода (в идеальном мире они уживаются вместе, но надо смотреть реально). Как фанатику, наверное, больше - первый, однако я совершенно не представляю, как вы сможете пройти по этому пути дальше, если пожелаете развивать проект после курса тфя. Но чего я точно не хочу видеть - это иллюстрации только тех алгоритмов, известных ещё с классической книги Ахо-Ульмана, которые уже многократно разобраны индусами и реализованы во всяких альтернативных проектах. Поэтому предложенные варианты Л.Р. 3 касаются первого направления.

**Comment by TonitaN** [comment]
Так, у Проскурникова народ уже решил, какие варианты делает, хотя я только пару часов назад им написала, из чего выбирать, а у вас всё ещё дискуссии? Записываемся, не тормозим - помним, что время лабы номер 3 уже пошло, и в этот раз я не особенно расположена продлять дедлайны, т.к. конец семестра всё ближе.

**Comment by StarikTenger** [comment]
Предварительное распределение
| Tables   |      Are     
|----------|:-------------:|
| @StarikTenger  | `капитан`  `документация` `старые баги`  |
| @alina8031  |   `документация`  |  
| @xendalm  |   `боцман`  `тест минимальности НКА по глейстеру` | 
| @Robby-the-paladin | `переход к регуляркам над интервалами от регулярок` | 
| @mathhyyn  |  `REPL + алгебра автоматов` `тестирование` | 
| @dak151449  | `префиксная грамматика по нфа` | 
| @shevchenkokk  |  `1-однозначность по бренингему` | 
| @xtoter  | 🤔 хто я (pending...) |

**Comment by TonitaN** [comment]
Я полагаю, что @xtoter скучает без алгебры, т.к. именно он реализовывал моноид. Надо продолжать добрую традицию, а там, может, и регулярки с отрицанием подтянутся (в этих регулярках, конечно, придётся переделать производные, а в методы regex->nfa (возможно, кроме антимирова) добавить построение подавтомата для отрицания). Зато это классная тема, которую индусы не показывают, а в реальных регулярках она есть.

**Comment by xendalm** [comment]
А в 8 варианте надо реализовать алгоритм, который у нас был в курсе дискретной математики, я правильно понял?

**Comment by TonitaN** [comment]
Алгоритм Хопкрофта и инкрементальный алгоритм Уотсона, ссылки будут. В дискретной математике скорее всего была вариация первого - там ведь O(n log n) оценка?
Ну и парсинг по НКА доделать придётся в этом же варианте (алгоритм Томпсона).

**Comment by xendalm** [comment]
Кажется, я сам запутался и у нас все-таки был кубический🙈

**Comment by TonitaN** [comment]
Кстати, документацией (функций, а не тайпчекера) можно фармить дополнительные баллы и в других вариантах, кто пожелает. Но на это будет только от +2 (а лучше -- от +3) до +4 баллов за функцию, т.к. если вы хотите дополнительные баллы, то уровень документации уже должен быть достаточно хорошим, чтобы за вами не пришлось переделывать тем, кто будет заниматься ею уже по долгу службы.

**Comment by xendalm** [comment]
Подразумевается документация к функциям аналогичная той, которую вы приложили в #130 (автомат глушкова)?




> в других вариантах

Это значит не вариант "документация"?

**Comment by TonitaN** [comment]
> Это значит не вариант "документация"? (можно ли свои функции документировать)
Конечно, можно. Всем желающим - удачи в первых шагах в латексе, кто ещё их не сделал (т.е. не был в ИПС).

**Comment by TonitaN** [comment]
Если об СПО в высшей школе, то нужно доделать:
1. трансмоноид с логами трансмоноида, туда же логи Майхилла-Нероуда и Глайстера-Шаллита
2. ускорить и поправить `PumpLength` (с меня алгоритм) с логами, и `SemDet` (для этого перепроверить Ардена), а также 1-ambiguity (тоже моя задача посмотреть, как там правильно извлекать регулярку) - для всего нужны нормальные логи.
3. исправить `Annote`, чтобы иметь возможность показывать на примере лемму об НКА. Отладить логи разных НКА, а также добавить логи удаления эпсилон-правил, обращения (переворота), детерминизации и минимизации. А ещё исправить ловушку! Можно криво, записать нормальное исправление в todo-лист.
4. Cделать тот самый проверяльщик гипотез (с исправлением порождения случайных тестов), о котом речь шла ещё в первой лабе.
5. Сделать рендер автоматов.
6. Сделать автопорождение уже отформатированных логов.

Что можно задвинуть:
1. `Normalize` :(( 
2. Алгебру автоматов и REPL (это хорошая вещь, но не горит)
3. Метаданные для генератора и тайпчекера (необходимо для жизни проекта, но задвигается куда-то в район курсачей, что мне не нравится, т.к. получится, что в следующем году никого не удастся привлечь с курса по ТФЯ, т.к. проект будет ещё нерасширяемый - но се ля ви)

1-6 в списке выше - это не номера вариантов, т.к. там есть пункты, которые тянут на лабу (например, 5 и 6), и пункты, которые не тянут на неё или вообще относятся к доделыванию старого функционала.
