### ISSUE TITLE
Разбить проект на статичекие библиотеки

### ISSUE THREAD

**Issue by StarikTenger** [StarikTenger/Chipollino#113]
Необходимо разбить проект на статические библиотеки, чтобы модули можно было подключать отдельно

Выделить стоит следующее:
* Объекты
* Интерпретатор
* Генератор тестов
* InfInt
* Fractions

[Похоже на то, что надо для **cmake**](https://github.com/ttroy50/cmake-examples/tree/master/02-sub-projects)

**Comment by StarikTenger** [comment]
Пока что предлагается такое разбиение. Всего будет 3 конечных модуля, из которых будет собираться executable:
* Интерпретатор
* Генератор тестов
* Юнит тесты

Остальные модули будут статическими библиотеками

![изображение](https://user-images.githubusercontent.com/48261272/201209945-743f92b9-cfe8-475b-8ced-d655c0ba252d.png)

**Comment by TonitaN** [comment]
Генератор тестов точно логично держать отдельно. С логгером вопрос: если добавится документация, то лог будет собираться из кусков документации и конструкций логгера. С другой стороны, конструкции логгера по смыслу встроены в основные объекты. Есть мысль сделать в основном модуле примитивный логгер (в стиле проекта @Qmask26), на базе которого уже работает теховский со всеми необходимыми фичами. Тогда работу над улучшением логов можно будет вести компактно в одном модуле, а не таскать по всем остальным.
