### ISSUE TITLE
Логирование ф/и Equal в динамическом тайпчекере 

### ISSUE THREAD

**Issue by mathhyyn** [StarikTenger/Chipollino#121]
ТЗ:
![image](https://user-images.githubusercontent.com/79749959/201228267-748708df-c816-4f7d-8e2a-49d49a0d2bf1.png)

`N1 = Annote.Minimize.Glushkov bb* !!`
не вызывается equal (из-за несовпадения по типам)
(автомат не изменился, сообщения об этом не вывелось в консоль (а можно в логгер, кстати, добавить (вообще все сообщения об ошибке интерпретации входных данных лучше добавлять в отчет, чтобы упростить дебаг)))
`N1 = Complement.Minimize.Glushkov bb* !!`
equal в конце вызывается и логируется (не должно)

Текущая реализация:
![image](https://user-images.githubusercontent.com/79749959/201227523-1ac3246a-9c70-4ec8-99bc-253af5f1b440.png)

P.S хотелось бы вывод на латинице, моя консоль не воспринимает русские буквы

**Comment by mathhyyn** [comment]
Надо либо получать от логгера флаг активации (сейчас он приватный), либо интерпретатору запоминать был ли указан '!!'

**Comment by xendalm** [comment]
Сейчас логи считаются вложенными, если они находятся внутри `init_step` - `finish_step`. Но в данном случае нам не нужно начинать шаг. Можно сделать отдельные функции логгера, которые будут только менять флаг. Между ними интерпретатор сможет делать свои проверки. Может и не только в интерпретаторе это пригодится
