### ISSUE TITLE
Динамическая проверка на детерминированность

### ISSUE THREAD

**Issue by mathhyyn** [StarikTenger/Chipollino#123]
сейчас статический тайпчекер не принимает последовательность dfa<-nfa

**Comment by StarikTenger** [comment]
Насколько я понимаю, в таком случае нам надо сделать статический тайпчекер отключаемым. Т.е. в интерпретаторе должен быть флаг, отвечающий за эквивалентность типов dfa-nfa

**Comment by mathhyyn** [comment]
Можно ли вообще оставить только тип fa?
И проверять на детерминированность только непосредственно перед функциями, которые принимают на вход dfa?
