### ISSUE TITLE
Баг конструктора копирования регулярок

### ISSUE THREAD

**Issue by mathhyyn** [StarikTenger/Chipollino#126]
```
N1 = Glushkov (a|b)b !!
```

на этапе лексера регулярка `(a|b)b` превращается в `a|bb`
причем с `a(a|b)b` проблем нет

Еще пример: `b*|(b*b)b`

![image](https://user-images.githubusercontent.com/79749959/201496174-4dabb605-1ef8-4974-b580-762099d3dd6b.png)
вывод перед return lex
вывод после выполнения scan_regex
Теряюсь в догадках((

Возможно дело в копировании..

EDIT:
Проблема нашлась!
![image](https://user-images.githubusercontent.com/79749959/201519151-ae1bd221-b99c-4823-a462-f7c144d3e1f5.png)
![image](https://user-images.githubusercontent.com/79749959/201519199-a64822d9-5334-4c19-95ff-c794e5649829.png)
конкатенация где-то неправильно происходит

**Comment by mathhyyn** [comment]
![image](https://user-images.githubusercontent.com/79749959/201363346-e41479b9-b1a3-474f-ba2c-eb57b9d4a22e.png)
необъяснимый феномен, автомат строится по исходному регулярному выражению
![image](https://user-images.githubusercontent.com/79749959/201364256-fb416359-b8a9-46cb-b751-765391742bbc.png)
????

**Comment by xendalm** [comment]
А здесь какая последовательность команд?

**Comment by xendalm** [comment]
Проблема в конструкторе копирования Regex

![image](https://user-images.githubusercontent.com/35781938/201535119-c7a2524a-624c-4265-9edd-12a8d32aa466.png)
![image](https://user-images.githubusercontent.com/35781938/201535129-53c742c2-94c1-4755-aef4-3a1082d102be.png)
