### ISSUE TITLE
Поддержка пустого языка

### ISSUE THREAD

**Issue by mathhyyn** [StarikTenger/Chipollino#134]
Проблема возникает после выполнения Complement
Исходный автомат:
![output17](https://user-images.githubusercontent.com/79749959/201549906-5b07d304-9939-4bd9-8358-d4e29cf32a16.png)
Результат:
![output18](https://user-images.githubusercontent.com/79749959/201549915-6ba43830-c8ac-4daa-8b51-ab6c0bfb9387.png)
получилась одна сплошная ловушка))0))0) (отсылка на предыдущий семинар)
если применить, например, reverse, то вылезет ошибка

**Comment by TonitaN** [comment]
Тут тонкий момент достаточно: алфавит всего из одной буквы у этого автомата. И поскольку он принимает абсолютно все слова, то и дополнение будет сплошной ловушкой (т.е. нет слов в унарном алфавите, которые бы этот автомат не принимал). 
Надо учитывать, что получился автомат, распознающий пустой язык. Однако с этим автоматом можно продолжать работать, и его дополнение будет опять нормальным автоматом, т.к. в нашем распоряжении есть такая сущность, как алфавит!

**Comment by TonitaN** [comment]
Вообще, по-хорошему надо, чтобы получалась именно нормальная ловушка, а не разветвлённая, т.к. только из одного состояния, но без конечных.
