### ISSUE TITLE
Не запускать интерпретатор (вариант для дин.тайпчекера - обрывать интерпретацию) при ошибке в типах

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#143]
Вообще метод Annote в ТЗ предполагался только для НКА (его можно расширить и на regex, если строить автомат Глушкова для них, делать в нём Annote, и обратно сопоставлять размеченные состояния с буквами исходной регулярки, но в ТЗ это не предполагалось). Когда он применяется к regex, получается весело:
```
N1 = Annote (a*)a*(a*)*
N2 = Glushkov N1 !!
```
Автомат размечает регулярку вида `N1` ))

Или Annote regex тогда уж добавить надо, или тайпчекером такое запретить.

Второе - нет линеаризации, и лексер падает:
```
N1 = Linearize (a*)a*(a*)*
N2 = Determinize.Glushkov N1 !!
N3 = Linearize N2 !!
N4 = DeLinearize.DeLinearize N3 !!
```

**Comment by mathhyyn** [comment]
1.
```
N1 = Annote (a*)a*(a*)* !!
N2 = Glushkov N1 !!
```

Тайпчекер не может построить последовательность => N1 не является идентификатором. Интерпретатору остается распознать N1 только как регулярку.
![image](https://user-images.githubusercontent.com/79749959/202153073-0b3a49be-cdb7-4148-8409-69571c584f04.png)


2.
Да, сейчас Linearize работает некорректно (будет исправлено)
![image](https://user-images.githubusercontent.com/79749959/202154235-8e766b12-bf76-45a5-82c0-a346d9cffce8.png)

Но все остальное верно
![image](https://user-images.githubusercontent.com/79749959/202154456-07838bd0-6cf2-4ffb-8b21-51d143d19871.png)
![image](https://user-images.githubusercontent.com/79749959/202154158-706fb629-f45f-4a97-b8e0-e3c5301e1f5a.png)
(аналогично 1 примеру)

а Linearize для автомата не реализован
![image](https://user-images.githubusercontent.com/79749959/202154973-40332a52-46fa-4e5b-8a54-35aec3263659.png)

**Comment by TonitaN** [comment]
То, что `Linearize` для автомата быть не должно - это правильно. А вот то, что после ошибки в проверке типов данных что-то всё-таки вычисляется (и притом ещё идентификаторы становятся регулярками, хотя косяк был именно в том, что пользователь ввёл не типизирующуюся последовательность), надо исправить, при статическом тайпчеке уж точно отказываясь что-либо вычислять. А при динамическом в этом случае объявлять конфликт имён и прерывать выполнение на том шаге, на котором этот конфликт возник (как в #148 , где регулярка совпала с именем переменной).
