### ISSUE TITLE
Ambiguity revisited

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#144]
Всё идеально тут:
```
N1 = a*a*((a)*)* !!
N2 = Glushkov N1 !!
N3 = Thompson N1 !!
N4 = Ambiguity N2 !!
N5 = Ambiguity N3 !!
```
Но проблема с неравномерным ростом числа путей от длины слова:
```
N1 = a*((ab)*)* !!
N2 = Glushkov N1 !!
N3 = Thompson N1 !!
N4 = Ambiguity N2 !!
N5 = Ambiguity N3 !!
```
Автомат Томпсона объявляется полиномиальным (он очевидно экспоненциален, т.к., вырастая на 2 буквы в длину, слово может либо вырасти на 2 буквы `aa` - это даст линейный прирост относительно предыдущего случая, либо вырасти на суффикс `ab` - это даст как минимум удвоение числа путей относительно предыдущего случая). Причем на регулярке `a*(b*)*` всё супер, и Томпсон верно объявляется экспоненциальным. 

А вот тут на вычислении `N5` интерпретатор слишком надолго задумывается (дождаться результата не удалось):
```
N1 = (a|b)*(f*)*q !!
N2 = Glushkov N1 !!
N3 = Thompson N1 !!
N4 = Ambiguity N2 !!
N5 = Ambiguity N3 !!
```

Если никак не удаётся исправить, то можно для простоты рассмотреть альтернативное определение меры неоднозначности (вместо неоднозначности в среднем,  как у вас, неоднозначность в худшем случае) и считать не от числа всех слов длины `n`, а от максимального числа разборов для слова длины `n`. Тогда эту меру можно будет сосчитать быстрее и проще (настолько проще, что она вообще станет определяться локально по автомату), но она будет более "теоретической конструкцией", т.к. вероятность попасть на слишком плохое слово может быть очень низка относительно числа слов в языке, как в регулярках вроде `(a|b|c|d)*(f*)*z`.

**Comment by xendalm** [comment]
Указанные проблемы, кажется, исправлены
