### ISSUE TITLE
Число итераций в методе `Test`

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#145]
```
Test (aab)* (a|)b 4
```
Почему-то только одна итерация. Баг найден благодаря генератору @mathhyyn :)

**Comment by mathhyyn** [comment]
во втором регулярном выражении нет звезд, т.е. оно никак не будет изменяться, значит нет смысла выводить все 13 итераций, но могу убрать это условие

**Comment by TonitaN** [comment]
Тут вопрос двойственный и сильно зависит от того, что более интересно:  "теоретические" или практические конструкции. В теории, разумеется, константная строка всегда будет парситься по регулярке за одно и то же время, и нужно делать одну итерацию. Но на практике при применении недетерминированных типов данных и парсингу по НКА (недетерминированному!) время работы алгоритма на одной и той же строке может различаться от случая к случаю даже экспоненциально. Это хорошо было видно во второй лабе, кто делал дополнительное задание к ней. Нужно очень внимательно посмотреть, оказывают ли какое-нибудь влияние типы данных а ля set именно на этот алгоритм парсинга, и если нет, то добавить это в документацию (что парсинг у нас по определению детерминирован) и придерживаться этого и дальше, а если влияют (и появляется недетерминизм) - то выводить все 13 итераций.
