### ISSUE TITLE
Вопрос насчёт `AutomatonToImage`

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#153]
Ни на чём не настаиваю, но питоновский `dot2tex` позволил бы более гибко управлять отрисовкой автоматов: разбивать длинные списки состояний на таблицы, порождать индексы, масштабировать графы и т.д. Сейчас у себя подключила для интереса его в соответствующем модуле - ну да, есть момент с встраиванием картинок в код и пара моментов с масштабированием, но не так они страшны. Если были причины, по которым решено отказаться от этой утилиты, можно высказаться в комментариях. Может, придумается какое-то решение найденных проблем, а если нет - будет принято имеющееся.

**Comment by TonitaN** [comment]
Да, и всё равно про это будет часть вариантов 5 лабораторной, так что возможно и стоило бы попробовать на примитивном уровне сделать это уже сейчас )

**Comment by alina8031** [comment]
Отказались от этой утилиты, потому что не хотели встраивать питоновский код в плюсы.

**Comment by TonitaN** [comment]
А обсуждалось же, что раз на плюсах ничего не нашлось, то можно и питоновский - помните, вы спрашивали? На плюсах мне правда ничего не удалось найти.

**Comment by alina8031** [comment]
Да, помню. Просто потом нашелся способ строить графы через команду консоли, он показался более лаконичным.

**Comment by TonitaN** [comment]
Он действительно более лаконичный, и кстати, для внутреннего тестирования подходит как нельзя лучше. Однако для отрисовки интерактивной документации можно попробовать подключить и трансляцию в tikz (повторюсь, на совершенно базовом уровне, т.к. 3 лабораторная пока что не про это). Впрочем, этим заниматься не обязательно, если найдётся способ сделать всё красиво внутри dot-формата (правда, там тоже есть проблемы с масштабированием, и не так удобно будет делать автоматы с "легендой" - а они нужны, если меткой узла является достаточно большое множество состояний). Я не настолько хорошо знаю Graphviz, но есть ли там возможность сделать метки узлов и рёбер в стиле LaTeX-а?

**Comment by TonitaN** [comment]
Поддержка гибкого форматирования индексов, например.

**Comment by TonitaN** [comment]
Вот какой результат получается с `svg` пакетом (метки в html не переводила, это уж сами):

[slide_documentation.pdf](https://github.com/StarikTenger/Chipollino/files/10042177/slide_documentation.pdf)

Даже лучше, чем с `dot2tex`, и меньше легаси багов. Правда, с метками придётся повозиться, и как по мне, Inkscape больше грузит память и работает медленнее, чем переписывание в tikz, но свои минусы есть у всех решений.

**Comment by TonitaN** [comment]
Проблема с `svg` (и не только в техе): кривые нижние и верхние индексы при размеченных по таблице метках узлов. Делала сейчас на работе генератор деревьев доказательств и убедилась, что получается боль и печаль (очень некрасивые лишние интервалы). Если эти проблемы решить не удастся, то чиполлино придётся либо dot2tex юзать с его легаси багами, либо выставлять высокий DPI параметр при генерации, чтобы не получалось слишком пиксельно.
