### ISSUE TITLE
Добавление метода порождения префиксной грамматики по НКА.

### ISSUE THREAD

**Issue by dak151449** [StarikTenger/Chipollino#155]

**Comment by TonitaN** [comment]
Метод работает корректно, но как по мне, правил переписывания получается слишком много (можно обойтись меньшим количеством). Скажем, рассмотрим вот такой автомат (даже детерминированный, для удобства):
![output1](https://user-images.githubusercontent.com/13885019/204411930-63868e68-bb4c-4571-a82a-7c3755acfeee.png)
Тут 0 стрелок в `S`, 4 стрелки в `a1`, 2 стрелки в `b2`, 4 стрелки в `c3`, и одна стрелка в `a4`. То есть если трансмоноид без багов, по идее алгоритм даст всего 11 правил переписывания:
```
a -> eps a
a -> a a
a -> ab a
a -> ca a
ab -> a b
ab -> ab b
c -> eps c
c -> a c
c -> ab c
c -> ca c
ca -> c a
```
Я их технически по алгоритму со слайда переписала (предполагая корректность трансмоноида), и их ещё можно уменьшить, убив идентичные типа `ca -> c a`. Легко увидеть, что все они у вас есть, т.е. ваша грамматика точно порождает все необходимые слова (только ещё нужно сообщить, как выглядит набор базисных слов). Однако там появляются ещё классы `ac` (который совпадает с `c`), `aba` (совпадающий с `a`) и многие другие. Есть подозрение, что ваше преобразование замкнулось по транзитивности, т.е. если есть правило `c -> ac` и `c -> abc`, тогда нужно добавить `ac -> abc`. Но это вовсе не обязательно делать, т.к. префиксная грамматика не станет при этом определять другой язык. Она только даст возможность переписывать слова большим числом способов.

**Comment by dak151449** [comment]
@TonitaN набор базовых слов - это просто вывести классы эквивалентности у состояний, которые финальные в автомате?

**Comment by TonitaN** [comment]
Да, это те классы, которые принадлежат языку.

**Comment by dak151449** [comment]
Ок

**Comment by dak151449** [comment]
@TonitaN, добавил вывод базовых слов и, вроде правильно, сократил правила.

**Comment by dak151449** [comment]
![image](https://user-images.githubusercontent.com/77326286/205644855-7449a7f8-a068-4b0a-97e7-a612b90892bd.png)

**Comment by TonitaN** [comment]
Завтра (которое сегодня) беру на проверку.
