### ISSUE TITLE
Тест минимальности НКА по Глейстеру-Шаллиту

### ISSUE THREAD

**Issue by xendalm** [StarikTenger/Chipollino#161]

**Comment by TonitaN** [comment]
Почему такая метка? ))

**Comment by TonitaN** [comment]
Чем отличаются таблицы, которые печатаются этими двумя методами?
```
	TransformationMonoid sm = fa.get_syntactic_monoid();
	cout << sm.to_txt_MyhillNerode() << endl;
	cout << fa.get_classes_number_GlaisterShallit() << endl;

```
По идее, Глейстер-Шаллит даёт результатом уже перестановку единичной матрицы, а не ту же матрицу, что трансмоноид.

**Comment by xendalm** [comment]
Ой, это старый пример, тут просто для дебага выводил таблицу. Теперь она автоматом выводится в методе `get_classes_number_GlaisterShallit`, потом уберу. Но пока даже вам так удобнее смотреть) 
А сам метод возвращает только число.

**Comment by TonitaN** [comment]
На первый взгляд, в реализации не хватает в препроцессинге выбрасывания из таблицы, построенной моноидом, одинаковых столбцов (их бывает очень много). Возможно, я просто невнимательно смотрела, но если нет, то нужно добавить эту оптимизацию.

**Comment by xendalm** [comment]
Действительно, пока нет. Добавлю

**Comment by xendalm** [comment]
Нужно ли это делать еще на уровне трансформационного моноида, вне зависимости от вызова моего метода?

**Comment by TonitaN** [comment]
Раз уж всё равно переоткрывать эту тему, то итоговую матрицу в дебаг выводите тоже.

Ну в трансмоноиде в принципе это тоже было бы сделать логично, но критическое влияние на время они там не оказывают. И я уже боюсь трогать @xtoter , у него и так слишком много дел )

**Comment by xendalm** [comment]
Мне нужно выводить таблицу МН с переставленными строками и столбцами?

**Comment by TonitaN** [comment]
Не совсем с переставленными, а с теми, которые остались в минимальной матрице. В любом случае для логгера понадобится эту таблицу передавать.

**Comment by TonitaN** [comment]
Завтра (которое сегодня) беру на проверку.
