### ISSUE TITLE
Баги ТМ

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#181]
Из-за них приходится откладывать проверку целых 2 лабораторных номер 3, поэтому актуалочка.

1. Классы эквивалентности теряются:
```
X = MyhillNerode.Minimize.IlieYu {ab|b} !!
```
Почему-то исчезает класс `b`, мапящий состояния так: `S -> b2`.

2. Ещё мне не нравится неинвариантное поведение на автоматах с ловушкой и без неё.
Так автомат определяется как минимальный (классов два, в этом смысле вроде ок). Он и вправду минимальный, а ещё он trim.
```
X = MyhillNerode.Annote.IlieYu {(ab)*} !!
``` 
Так нет :( Минимальный, но с ловушкой.
```
X = MyhillNerode.Minimize.IlieYu {(ab)*} !!
```
С последним багом я не знаю, кому разбираться. Но если там вместо нормального решения будет использовано "даёшь зазор в одно состояние, в рамках которого минимальность подтверждается", то все ведь понимают, чем это кончится при проверке?

**Comment by TonitaN** [comment]
И просьба к @xtoter хотя бы ненадолго отключить режим троллинга: мы уже поняли, что смотреть коммиты нужно внимательнее, и желательно втыкать побольше юнит-тестов для новых функций, если их недостаточно от автора. Учли, исправляемся. Пощадите нас с @xendalm , пожалуйста, и не подкидывайте свеженьких багов - вот когда опять начнём невнимательно смотреть, можете фишку с багами повторить.

**Comment by xtoter** [comment]
@TonitaN  Спешу сообщить что вроде работает (еще не сломано), тестировалось на 1000 рандомных регулярках, появилось  ̶б̶о̶л̶ь̶н̶а̶я̶  идея завести рефальские тесты. Вроде исправлены обе ошибки.
![image](https://user-images.githubusercontent.com/76103754/205266920-43421a6b-270b-425f-9e2e-a4d2344554de.png)

**Comment by TonitaN** [comment]
Поздравляю! Вечером буду тестить. 

А от природы ~~тролля~~ не убежать... Какой PR вы прилинковали к этой теме, все заметили?

P.S. - Мы все тут больные, поэтому идея про рефальские тесты мне нравится (и на фронтенде рефал пригодился бы) - думаете, как я тестирую большую часть лабораторок на нагрузке?
