### ISSUE TITLE
Автомат не минимален, а Minimal = true (или как повысить уровень тролля сразу всеми)

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#191]
Если я такой автомат объявлю минимальным на паре по ТФЯ, интересно, что мне скажут:

![trapik_1](https://user-images.githubusercontent.com/13885019/206421249-cbb1b3ad-953f-47cf-b626-da607bbc64ab.png)

Народ, вы пока не сеньоры и не теоретики, чтобы лечить код волшебными костылями. Исправляйте уже этот баг по-человечески, понимаете ведь, что на нём ещё баги нарастают.

**Comment by xendalm** [comment]
Вы проверяете его методом моноида или is_dfa_minimal?

**Comment by TonitaN** [comment]
Моноида )

**Comment by TonitaN** [comment]
Так очевидно же, что решение, озвученное @xtoter : "удалить все ловушки и проверить минимальность результата" будет лагать, если ловушек может быть больше одной. Предупреждала же, что сломается - не поверил :(

**Comment by TonitaN** [comment]
Ахаха, я повысила уровень троллинга минимум на 1. Два дня назад, на радостях, что сломался трансмоноид, я прикрепила неправильную по счёту из логов картинку автомата, и никто, включая меня, не заметил, что он таки минимальный 🙈 Теперь контрпример выглядит правильно, а троллизм надежно спрятан в EDIT-ах 👀.

**Comment by TonitaN** [comment]
Возвращаемся к старому доброму бесконечному тестированию трансмоноида (@xtoter , надеюсь, вы уже сдали всю алгебру и скоро возьмётесь за допуск по ТФЯ?)
```
	Regex r("(ab|ac|ba|bc|ca|cb)");
	TransformationMonoid a1(fa1);
	cout << a1.get_classes_number_MyhillNerode() << endl;
```
По минимальному автомату видно, что там должно быть 5 состояний, а находится только 4 класса.

**Comment by xtoter** [comment]
> (@xtoter , надеюсь, вы уже сдали всю алгебру и скоро возьмётесь за допуск по ТФЯ?)

После пятницы я полностью принадлежу этому проекту и курсачу🤖 (надеюсь все так)

**Comment by TonitaN** [comment]
По-видимому, действительно фишка - в ТМ для НКА. Надо аккуратно перепроверить, почему там исчез класс эквивалентности `c` и почему в некоторых позициях, где должны стоять единицы (например, на строке `a` и столбце `c`) стоят нули.
```
        a   b   c   ab  
    0   0   0   0   1   
a   0   0   1   0   0   
b   0   1   0   0   0   
ab  1   0   0   0   0   
```
