### ISSUE TITLE
ПГ для НКА (трансмоноид и не только)

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#193]
На ДКА багов найти пока не удалось, а вот на НКА проблемы у двух алгоритмов сразу.
Пример: `IlieYu {(a|b)*a}`
![output2](https://user-images.githubusercontent.com/13885019/206068951-cd960c90-f22c-42f1-97ff-0c4351381e6d.png)

Результат (одинаковый на двух методах):
```
a -> a a
a -> a b
a -> b a
a -> b b
b -> a a
b -> a b
b -> b a
b -> b b
```
Базовое слово: `a`. 
Видно, что, например, правило `a -> bb` превращает слово из языка в слово не из языка.
Почему такое происходит с трансмоноидом, разобраться, кажется, удалось. Дело в том, что теперь разным путям из `S` в `qi` могут соответствовать одни и те же слова. Рассмотрим трансмоноид для нашего автомата:
```
Term	a	in	language	1
S	->	S
S	->	a3
Term	b	in	language	0
S	->	S
```
Получается, что `a` представляет целых два префикса: для `S->S` и для `S->a3`. И если первый мы бы могли спокойно переписывать в `b`, то второй так уже нельзя. Заметим, что в случае ДКА такой конфликт был бы невозможен.

То есть проблема в трансмоноиде для НКА концептуальная, и надо её решать.

Положим, мы будем выбирать в качестве базисных не все классы эквивалентности, а только наименьшие по длине для данного `qi`.  И при этом не забудем про тривиальный класс эпсилон, которого в трансмоноиде нет (кстати, совершенно не очевидно, что в трансмоноиде для НКА его не надо делать - с этим ещё придется разбираться), и который всегда является базисным для `S -> S`.
То есть для нашего автомата были бы выбраны классы:
- `eps` для `S -> S`
- `a` для `S -> a3`
И всё, дальше переписывание произошло бы корректно.

Это частично пофиксит баг (и заодно сильно уменьшит число правил в грамматике), но всё равно может оказаться, что у двух префиксных путей самый короткий класс эквивалентности выглядит одинаково. Пример ниже:
![output2](https://user-images.githubusercontent.com/13885019/206071359-cd32728d-c66e-43c0-95c8-02f12d6ed30c.png)
Проблема с классом эквивалентности `a`. Причём если для состояния `a4` мы могли бы выбрать ведущим класс `b` (ему соответствует единственный префиксный путь), то с состоянием `a1` непонятно как поступать. Все классы, которые мапят `S->a1` (а конкретно класс `a`), мапят `S` куда-то ещё. И проблема даже может не решиться рекурсивным расширением суффиксов, если в автомате окажутся две почти идентичные ветки (а ещё с эпсилон-правилами будет всё плохо). Поэтому в таких случаях предлагаю вывести в логе предупреждение, что обнаружена неоднозначность в префиксных путях, и грамматика будет построена для ДКА, полученного детерминизацией из данного НКА. После чего вызвать детерминизацию и построить ПГ уже по проверенному алгоритму. 

Кстати, на следующем автомате:
![output4](https://user-images.githubusercontent.com/13885019/206074311-d98eae46-a925-46f5-af7e-89a21353b6d5.png)
(полученном детерминизацией из предыдущего)
трансмоноид-метод дал очень красивый и правильный результат (за счёт игнора ловушки). 
```
a -> eps a
aa -> a a
aa -> b a
ab -> a b
ab -> ab b
b -> eps b
```
А первый метод дал кучу избыточных правил, регламентирующих поведение ловушки. Я так понимаю, что если взять автомат с несколькими ловушками, ПГ будет описывать поведение каждой из них %) Это с точки зрения порождаемого языка не ошибка, но порождает много недостижимых правил - то есть баг проектирования.

**Comment by xtoter** [comment]
> То есть для нашего автомата были бы выбраны классы:
> 
> * `eps` для `S -> S`
> * `a` для `S -> a3`
>   И всё, дальше переписывание произошло бы корректно.

ну по моим ощущениям это не звучит как фикс ибо хрень происходит (если ошибаюсь прошу пояснить), мы просто теряем кучу правил переписывания
![image](https://user-images.githubusercontent.com/76103754/210958416-fc316b46-361c-4a9d-9470-c3e868043d64.png)

**Comment by TonitaN** [comment]
Если хочется добавить `eps` в трансмоноид, то он соответствует переходам всех состояний в себя. И в примере выше этот `eps` не будет эквивалентен вообще никакому другому классу. Так-то у Пина эпсилон-класс добавляется в моноид для НКА, и это ничего не ломает. Кстати, он пользуется матричным представлением над булевскими значениями для представления НКА-моноида (квадратная матрица, где отмечено единицами, из каких состояний переход в какие возможен), возможно, это имеет смысл и более эффективно, чем использовать списки.

**Comment by TonitaN** [comment]
Здесь (для самого первого автомата) с классом эпсилон в трансмоноиде получится так:
1. eps - единичная матрица
2. a - матрица 
```
1 1
0 0
```
3. b - матрица
```
1 0
0 0
```
4. `aa -> a` (та же матрица), `ba -> a`, `bb -> b`, `ab -> b`
Как у вас получилось `aa -> b`? Я что-то не понимаю :(
