### ISSUE TITLE
1-однозначность разная на эквивалентных регулярках

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#195]
Лучше раньше, чем позже.

Смотрим:
```
M1 = Glushkov {(a|b)*a} !!
M2 = Glushkov {b*aa*((bb*aa*)*|)} !!
X = Equiv M1 M2 !!
```

Результат --- `true`. Однако модуль автотестов выдаёт на следующем коде:
```
        Regex r8("(a|b)*a");
	cout << "RE 8 " << r8.is_one_unambiguous() << endl;
        Regex r9("b*aa*((bb*aa*)*|)");
	cout << "RE 9 " << r9.is_one_unambiguous() << endl;
```
Результаты 0 и 1 соответственно.

Нетрудно понять, что язык действительно 1-однозначный, если посмотреть на второй автомат Глушкова (он детерминированный).

![output4](https://user-images.githubusercontent.com/13885019/206584970-b965be06-cad8-491f-82fa-4bc512ca6d76.png)

Возможно, проблема в том, что я тестирую старую версию, из главной ветки. Если теперь такой автотест отрабатывает правильно, то прикрепите новый реквест к теме, чтобы сразу закрыть её вливанием. Но есть шанс, что таки баг.

**Comment by shevchenkokk** [comment]
Разве `is_one_unambiguous` для регулярок не должен проверять 1-однозначность регулярки, а не языка?

**Comment by TonitaN** [comment]
Поняла, действительно, метод полиморфен. Надо было вызывать для автоматов.

**Comment by TonitaN** [comment]
Всё хорошо, метод работает )
