### ISSUE TITLE
Лабы номер 4 и 5 - варианты (не) для красоты

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#198]
Наиболее актуальный список вариантов лабораторных - ниже (двойные восклицательные знаки - варианты, которые точно нужно выбрать):
1. (!!) Рендер автоматов (отрисовка по наброску с комментариями с учётом порождения заранее неизвестного числа стилей). HTML-метки и адекватная вставка диаграмм в исходник (с учётом переполнений и нормального dpi). Если очень хочется красоты, можно вдвоём.
2. (!!) Порождение логов по шаблону. Дан шаблон в latex с разметкой в метаязыке, и логи, порождённые исполнением конкретного примера. Вписать логи в шаблон. То же самое - можно на двоих.
3. Шаблоны для функций `RemEps`, `Minimize`, `Determinize`, `Reverse`.
4. Шаблоны для функций `PumpLength`, теста минимальности (+ GlaisterShallit), производных.
5. Шаблоны для функций `isOneUnambiguous`, `Ambiguity`, `SemDet`.
6. (!!) Доделывание: генератор гипотез, исправление `Annote`+`DeAnnote` (и тех багов - именно багов, а не оптимизаций, - которые указаны в #169), исправление ловушек, расширение функционала интерпретатора, и своевременная интеграция всего, что сделано другими в 3-5 лабах. 
7. У @xtoter --- одна лаба точно без выбора: сделать `Normalize` и логи к Ардену и функциям трансмоноида. А поскольку у него сдано пока только две лабораторные, то это должно быть сделано обязательно. "Учись, студент" (с)
8. Составление метаданных (атрибутной грамматики) по функциям и автопорождение тайпчекера.

**Comment by TonitaN** [comment]
Недостающие шаблоны, если что, добьём уже с теми, кто на oseduconf собирается (кстати, если подаём заявку - а мы её подаём, если к 24 декабря будет сделано то, что помечено двумя восклицательными знаками, то как и обещала, всей группе +10 баллов на распределение и непосредственным участникам авансом по +5, но вот участникам придётся ещё добивать проект перед конференцией, так что пусть рассчитывают время). Сильно переживать об их отсутствии не стоит. 

И ещё - если мне не понравится то, как ваш код работает с шаблонами и рендерит автоматы, то будет страшное: рефал. Потому что на нём это делается быстро и красиво, и мне будет проще доделать этот функционал самой, чем стоять у вас над душой с бесконечными фиксами.

**Comment by TonitaN** [comment]
Решение по докладу можно сдвинуть на 31 декабря - они на неделю подвинули дедлайн. Лучше раньше, чтобы не думать об этом непосредственно 310го, а то потом весь год придётся заниматься ТФЯ, как некоторые заложники )) Но без спешки пока. Не очень хочется вас сейчас дергать от зачётов, кроме тех, у кого лаба будет только третьей по счёту.

**Comment by TonitaN** [comment]
Жёсткий таймлайн (иначе тезисы не успеем, там крайний срок 9 января, позже уже уйдём в баню):
- 3-4 января - делаю болванку для трансмоноида и бисимуляции (здесь могло быть что-то ещё, если бы было из чего выбирать)
- 5-6 января - если к этому моменту не сделан рендер автоматов по заготовке (нормальные метки, раскрашивание), сама делаю рендер автоматов
- 7 января - если к этому моменту не сделаны логи, делаю логи трансмоноида и бисимуляции
- 8 января - пишу тезисы. Уже, по-видимому, никого ни о чём не спрашивая, хотя изначально планировала согласовать.

Но те баллы группе за участие, которые я обещала, тем не менее выдам. Правда, с соответствующим далеко не новогодним настроением :(

**Comment by TonitaN** [comment]
Возник вопрос: может ли быть так, что два НКА бисимилярны, число их состояний совпадает, но после слияния по бисимуляции они не равны? @xendalm , может быть, вам попадался такой пример?

**Comment by xendalm** [comment]
Сейчас не вспомню, надо поискать

**Comment by TonitaN** [comment]
Ваш пример про неравные НКА с бисимуляцией и биекцией состояний, кстати, добавила в слайды документации (со ссылкой на вас).

**Comment by TonitaN** [comment]
Документация по бисимилярности (`Bisimilar` и `MergeBisim`):

[Bisimilarity.txt](https://github.com/StarikTenger/Chipollino/files/10347958/Bisimilarity.txt)

Итог (слайды):

[Bisimilarity.pdf](https://github.com/StarikTenger/Chipollino/files/10347965/Bisimilarity.pdf)

Есть тонкость с министраницами: делаем их параллельными, только если автоматы маленькие (до 9 состояний включительно). Если больше, то переносим каждый автомат на новый слайд. 

И да, я настаиваю, чтобы над болванками было минимум действий руками при преобразовании их в заготовки. Поменять болванку, добавить метаданные, и т.п. - пожалуйста. Копировать болванку несколько раз и модифицировать её под каждый отдельный вариант - пожалуйста, нееееет! Иначе даже мелкое косметическое изменение в документации будет болезненным. Ну если никак не получается сосчитать баланс скобочек (там есть несколько тонкостей, с учётом контекстно-зависимой грамматики латеха) - ну давайте я скрипт сделаю, который сделает это автоматически и добавит метаданные "скобка открывается" - "скобка закрывается" там где надо. Потом один раз через него всё пропустим и больше руками ничего делать не будем. Окей?

P.S. - Я уже поняла, что в следующем году основы рефала на ТФЯ дать придётся, чтобы народ не боялся работать с метаданными и знал, когда всё-таки можно использовать рефал-стиль.

**Comment by TonitaN** [comment]
Отдельный привет @StarikTenger , как-то высказавшему мнение, что логгирование - это тупая техническая задача. Она такая же "тупая техническая", как и тестирование бэкенда. Не нужно, пожалуйста, переносить стереотипы коммерческого программирования на научные и экспериментальные проекты - здесь всё с ног на голову, и мозги приходится прикладывать на каждом этапе.

**Comment by TonitaN** [comment]
Оффтоп: пруф насчёт программы ТФЯ в "ворде".

![TFL_Compromised](https://user-images.githubusercontent.com/13885019/210666916-06a11c69-ffdb-442b-9c2c-1b61dfea5009.png)

Просто студентам "ворд" не виден. А если открыть в браузере, то можно увидеть, что расширение у него очень интересное: `pdf.doc.pdf` 👀 Виват рефалу и *истинной сущности* ИУ9!

**Comment by TonitaN** [comment]
Нормальная документация к трансмоноиду к "дедлайну в 6 утра" не успевается, буду доделывать завтра :( 

Кто всё-таки взял рендер автоматов? Или никто, и у меня полная свобода делать его на рефале?

**Comment by TonitaN** [comment]
Документация к трансмоноиду:

[TransMonoid.txt](https://github.com/StarikTenger/Chipollino/files/10362043/TransMonoid.txt)

Тайпсет (слайды):

[TransMonoid.pdf](https://github.com/StarikTenger/Chipollino/files/10362047/TransMonoid.pdf)

Максимально приближено к тем исходникам, которые были у меня на момент её написания %) Чтобы относительно нормально можно было продвинутые логи извлекать. Если что-то всё равно не удобно, можно поменять. Но в любом случае логгировать таблицы надо будет.

**Comment by TonitaN** [comment]
Кажется, удалось локально (для наших целей) вылечить очень противный (и тянущийся уже несколько лет) баг парсера `dot2tex` небольшим изменением исходника + вставкой промежуточного скрипта постобработки. По-хорошему, там в исходнике в парсере надо поменять кое-что, но копаться в чужом коде (да ещё и не своих студентов) - это 🤢 Да и в любом случае в `PyPI` эти изменения никто не добавит, поэтому скрипт придётся использовать локальный.

Теперь должно работать для наших простых графов, но проверить надо на большом объёме данных.

**Comment by TonitaN** [comment]
[main.pdf](https://github.com/StarikTenger/Chipollino/files/10369096/main.pdf)

Отправляю. Тем, кто в НГ праздники сумел заставить себя продвинуться по проекту - персональное спасибо от меня: свет на горизонте наконец брезжит, и это не может не радовать. Всем отличных оценок на экзамене и постараться чуть-чуть перезагрузиться перед новым спринтом. А да, 10 баллов между собой распределите. Только не поровну, а по справедливости 🐝
5 баллов улетают @xendalm как докладчику ("герой должен быть один"), но ему они вообще не актуальны (до автомата всё равно не хватает что-то около 6 баллов, а на оценку уже не влияют).
Алине я сейчас проставлю зачёт по 3 лабе, хоть и немного авансом (пока не влились). У Ани тоже совсем близко. Мише +3 за рефакторинг, и расходимся.
