### ISSUE TITLE
Трансформационный моноид

### ISSUE THREAD

**Issue by xtoter** [StarikTenger/Chipollino#20]
Необходимо интеграровать Трансформационный моноид.
На вход алгоритма подаётся детерминированный конечный автомат.
функции:
- ClassLength (самое длинное слово в классе эквивалентности),
- ClassCard (число классов эквивалентности)
- MyhillNerode — число классов эквивалентности по М.Н.)

**Comment by StarikTenger** [comment]
Сразу лучше поправить несколько косяков:

1. Отступы делаются табами, не пробелами
2. Для методов используется *snake_case*. Ещё правильно писать *equivalence* (c на конце)
```c++
vector<Term> get_equalenсe_classes_VW(Term w);
vector<Term> get_equalenсe_classes_WV(Term w);
// и т.д.
```

3. С заглавной буквы называются только классы и константы
4. Не надо называть структуру `Perehod`, есть замечательное слово `Transition`
5. Между классами и функциями ставь переход строки
6. Перед `private:` и `public:` не надо ставить 3 пробела

**Comment by xtoter** [comment]
![image](https://user-images.githubusercontent.com/76103754/198741282-e9481104-997a-4335-9f6f-2622d2df35c7.png)
Прикольно сделали, а главное за день до дедлайна)

**Comment by xtoter** [comment]
Не соответствует формат функций преобразователя, нужны соответсвующие исправления

**Comment by TonitaN** [comment]
Что такое максимальная длина перехода в трансформационном моноиде?

**Comment by xtoter** [comment]
Если предполагается, что максимальная длина слова в моноиде k, то это она. На самом деле если точно известно что слов длины больше нет, то ставится это число, в ином случае ставится большее и при этом все корректно отрабатывает, наверное стоит убрать этот параметр.
