### ISSUE TITLE
Парсер регулярок

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#201]
Регулярка распознаётся как корректная (кусок `|*` из неё просто выкидывается).
```
G = Thompson {aa*|*a}  !!
```

**Comment by TonitaN** [comment]
А ещё игнорируются множественные звёздочки, если они не в скобках: `a*********` рассматривается как `a*`. Нужно либо запретить их использование явным образом в документации, либо корректно обрабатывать. Понятно, что двойная звёздочка в принципе действует так же, как и одинарная, но это уже упрощение в рамках алгебры регулярок, а парсер алгеброй заниматься не должен.

**Comment by mathhyyn** [comment]
программа аварийно завершается при
")", "*", ")*"
