### ISSUE TITLE
Annote + Linearize Fix

### ISSUE THREAD

**Issue by xendalm** [StarikTenger/Chipollino#209]

**Comment by xendalm** [comment]
Можно начинать исправлять функции :)

**Comment by mathhyyn** [comment]
буду кидать сюда напоминалки
беды Linearize:
1.
```
N2 = Reverse.Thompson.Linearize {(aa|ab)*} !!
```
![image](https://user-images.githubusercontent.com/79749959/210461182-b41630c5-73dd-416b-8793-99fc67aa21fa.png)
2.
```
N2 = Minimize.Reverse.Thompson {(aa|ab)*} !!
```
![image](https://user-images.githubusercontent.com/79749959/210461353-bab1e6c8-c353-4afd-9807-022974595e02.png)
```
N2 = Minimize.DeAnnote.Reverse.Annote.Thompson.Linearize {(aa|ab)*} !!
```
![image](https://user-images.githubusercontent.com/79749959/210461894-3d357b17-7e8e-4be1-837b-1f5952180ecc.png)
они должны быть разными?
3.
DeLinearize после преобразования в автомат не работает
```
N2 = DeLinearize.Thompson.Linearize {(aa|ab)*} !!
```
![image](https://user-images.githubusercontent.com/79749959/210462156-872380a0-7a8e-4e6d-b166-5e4866565444.png)
4. 
![image](https://user-images.githubusercontent.com/79749959/210462259-7046ed09-afca-4fbc-b792-31266e075b72.png)
тайпчекер сообщает о том, что 
* регулярка осталась неизменной, то есть `Equal {(aa|ab)*} (Linearize {(aa|ab)*})` оказалось true
(в интерпретаторе правда такой функции нет)
* автомат после DeLinearize изменился, но на деле этого не видно
![image](https://user-images.githubusercontent.com/79749959/210462573-2c8285e8-32f6-4b36-9c6e-ba590e69020e.png)

**Comment by mathhyyn** [comment]
Проверить, когда пофиксят Arden:
- [ ] 1.
```
N = DeLinearize.Arden.Annote.Thompson {(aa|ab)*} !!
```
```
N = DeAnnote.Arden.Annote.Thompson {(aa|ab)*} !!
```
- [ ] 2.
```
N = DeLinearize.Arden.Thompson.Linearize {(aa|ab)*} !!
```
- [ ] 3.
```
N = DeAnnote.DeAnnote.DeAnnote.Arden.Annote.Thompson.Linearize.Linearize {(aa|ab)*} !!
```

**Comment by mathhyyn** [comment]
ужас! а это еще до ардена не добрались
