### ISSUE TITLE
Проверка автомата на детерминированность и поиск ловушек

### ISSUE THREAD

**Issue by StarikTenger** [StarikTenger/Chipollino#21]
1. Реализовать метод 
```c++
FiniteAutomat::is_deterministic()
```

В *Automat* создать приватное поле `deterministic`. В процессе работы *is_deterministic()* должен поле изменять. Если поле уже вычислено, то, очевидно, надо просто вернуть соответствующее значение и ничего не считать

Флаг `deterministic` сделать через [std::optional](https://en.cppreference.com/w/cpp/utility/optional)

2. Реализовать методы
```c++
// Проверка состояния на ловушку
State::is_sink();
// Подсчёт ловушек в автомате
FiniteAutomat::get_sink_number();
```

В *State* добавить поле `optional<bool> sink`, определяющее, ловушка ли это состояние

В *Automat* добавть `optional<int> sink_number`, определяющее количество ловушек

**Comment by xendalm** [comment]
Нужно не забыть проверить/установить флаг
