### ISSUE TITLE
Гомоморфизм слайды->методичка

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#210]
~Под ёлкой~ экспериментирую с автоматическим конвертером. Результат уже приемлемый (с первого раза без подгонок получен по слайдам Глушкова, до этого подгонка была по слайдам ТФЯ, гораздо более непрозрачно оформленным).

[Dummy.pdf](https://github.com/StarikTenger/Chipollino/files/10322925/Dummy.pdf)

Но надо сделать лучше. Как минимум, учесть в метаразметке метки диаграмм (чтобы были корректно оформленные плавающие объекты). Ну и есть ещё всякие латеховские штучки, которые вполне реально учесть до 31-го, чтобы получилось что-то нормальное.

Угроза сбылась: оно на рефале. Поэтому если подключать этот прототип (а другого конвертера пока нет 😈), то нужно юникодовский рефал подогнать (передаём привет @xtoter ). Ну и конечно, вы можете сделать конвертер сами - но есть сомнения, что оно успеется. Не на рефале-то это писать сильно дольше 🌈

**Comment by StarikTenger** [comment]
Оказывается, в [new-logger](https://github.com/StarikTenger/Chipollino/issues/170) у нас уже 3 недели лежит рабочая версия...
Есть пара косяков с дизайном, но основной функционал работает

[log.pdf](https://github.com/StarikTenger/Chipollino/files/10326459/log.pdf)

**Comment by TonitaN** [comment]
Тестовая версия конвертера готова (работает с обычным рефалом, надеюсь, удастся перевести в UTF-8).

[Hom_Slides.ref.txt - потому что рефал прикреплять нельзя](https://github.com/StarikTenger/Chipollino/files/10332825/Hom_Slides.ref.txt)

На первых восьми лекциях по ТФЯ оно лагает в основном там, где я сама написала кривую разметку либо очень криво использовала способы постепенной отрисовки слайда (допустим, с копипастой). Руками я поправила только три позиции, причём все они связаны с командами `only`; кривые моменты в отрисовке. В конвертере есть отвратительные костыли с министраницами (которые пока никто не использует в документации), остальное приемлемо, переполнения по ширине в тексте пока ещё не обрабатываются автоматически, но это можно сделать в цикле `sh`-`ref`. Конвертер работает в режиме `a` (@xtoter поймёт) к исходнику `Dummy.tex`, чтобы можно было во-первых, приписывать сразу много слайдов из разных файлов, а во-вторых, локализовать преобразования внутри одного слайда, который по умолчанию замкнут на себе. В принципе, там есть потенциал к расширяемой преамбуле, однако это пока не реализовано. Было бы чем расширять, всё сделаем.
Кое-где есть злоупотребление рефал-стилем, однако для 81 страниц время работы весьма приемлемое из-за локализации по слайдам, и это на первый случай пойдёт.

[А вот тут результат конвертации слайдов ТФЯ. Выглядит баговато, но это если не смотреть на исходники слайдов... :)](https://github.com/StarikTenger/Chipollino/files/10332832/TFL_probe.pdf)

Поэтому по принципу сохранения локальной замкнутости лучше сначала генерировать исходник слайдов, а потом по необходимости переводить в чистый текст. 

Сейчас буду писать документацию к трансмоноиду и бисимуляции. Как напишу - нужно будет сделать логи для бисимуляции и трансмоноиду, чтобы хоть пару картинок в тезисы добавить :(  Автоматы, видимо, будем рефалом рендерить :(

**Comment by TonitaN** [comment]
Скрипт вызова:
```
testname=$1
echo Converting $testname ...
cp Header.txt Dummy.tex
 iconv -f UTF-8 -t WINDOWS-1251 < $testname > $testname-win
 refgo Hom_Slides $testname-win Dummy.tex
echo "\\end{document}" >> Dummy.tex
read -s -n 1
```
