### ISSUE TITLE
Прототип рендера автоматов

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#222]
**Конвертер из исходного `dot` в промежуточное представление** 
- [x] - выкинуть дубли из меток, чтобы не добавляли длину искусственно (надо было не на этом этапе, а ещё до записи в `dot`)
- [x]  - слишком длинные метки узлов заменить плейсхолдерами, их значение вынести в промежуточный файл с легендой;
- [x] - если какие-то метки слишком сильно меняют размер в мат.режиме, тоже заменить плейсхолдерами (вернуть на место уже в латехе) - оказалось надо, если вставляется таблица с переносом списка меток на несколько строк
- [x] - придумать, как сменить преамбулу в `dot2tex` (она захардкожена :( - если не найдётся решения лучше, придётся перезаписывать в постпроцессинге)

**Постпроцессинг `tikz`**
- [x] - заменить двойное обрамление узлов и стрелки на рёбрах с дефолтных на эстетически более приятные
- [x] - добавить раскраску узлов по группам из метаданных и порождение необходимых цветов с помощью `xcolor` (максимум 17 разных стилей, надо будет добавить предупреждение, что больше нет, да и не очень понятно, как большее количество различить на глаз)
- [x] - добавить легенды и параметры для длинных меток узлов и разбивку не самых длинных меток узлов на несколько строк
- [x] - переписать метки в мат.режим (Важно! этого нельзя делать до запуска `dot2tex`, иначе без режима `autosize` получится фигня, а этот режим использует пакет превью и работает меееедленно)

**Постпроцессинг `latex`**
- [x] - исходя из общего размера автоматов, рассчитать размеры обрамляющей министраницы (лучше сделать, т.к. абсолютные размеры рассчитать будет гораздо труднее)
- [x] - рассчитать при малом размере министраницы, что можно поместить по соседству (может вписаться другая диаграмма или таблица)
- [x] - при большом размере автомата - сделать адекватную разбивку по фреймам.
- [ ] - понять, как хранить закэшированные автоматы и доставать из кэша уже готовый `latex`-код (это уже более общая задача, которую пусть решает кто-нибудь другой 🦧).

Прототипы рендера в одном архиве:

[добавлена настраиваемая поддержка разметки Annote и Linearize и перегрузка запятой](https://github.com/StarikTenger/Chipollino/files/10473244/Renderer.zip)

**Comment by TonitaN** [comment]
Постпроцессинг `latex` пока идёт лесом, т.к. в связи с `IlieYu` всё равно нужны длинные метки и разбивка, и оно стоило того, чтобы его сделать.

Весь базовый функционал сделан, тизер результата с метаданными, разбивкой и легендой ниже:
 
[TM.pdf](https://github.com/StarikTenger/Chipollino/files/10367548/TM.pdf)

Можно с чистой совестью включать какую-нибудь подобную картинку в тезисы.

Большая часть времени убита на взаимодействие всего этого дела с `latex` и `dot2tex` (ох уж эти относительные зависимости в питоне :( ). Попытка обойтись без препроцессинга, только одной постобработкой, дала крайне печальные результаты. Поэтому пока только в режиме `Preprocess -> dot2tex -> Postprocess` нормально получилось.

Скрипты ниже. В них есть похожие куски в синтаксическом разборе, т.к. существует гомоморфизм `tikz` в `dot` (увы, не наоборот, иначе бы было всё совсем просто), и по идее нужно сделать разбор по параметризованной грамматике. Но дедлайн 6 утра через час, и вообще лнь.

[MathMode.ref.txt](https://github.com/StarikTenger/Chipollino/files/10367552/MathMode.ref.txt)
[Postprocess.ref.txt](https://github.com/StarikTenger/Chipollino/files/10367553/Postprocess.ref.txt)
[Preprocess.ref.txt](https://github.com/StarikTenger/Chipollino/files/10367554/Preprocess.ref.txt)

Скрипт запуска под виндой:
```
set arg=%1
refgo Preprocess+MathMode %arg%".dot" 2>error_refal
dot2tex -ftikz -tmath "Mod_"%arg%".dot" > %arg%".tex"  2>error_dot2tex
refgo Postprocess+MathMode %arg%".tex" 2>error_refal
```
После него остаются промежуточные метаданные, но добавить их стирание не проблема, а дебажить было сильно проще.

**Comment by TonitaN** [comment]
Да! Эксперименты показали, что препроцессинг рулит по скорости. `--autosize` в `dot2tex` работает оооооооооочень долго, а рефал даёт пренебрежимо малую задержку (несоизмеримо быстрее, чем даже базовый `dot2tex`). В целом скорость приемлемая и не бесящая даже для автоматов из 50 состояний.

**Comment by TonitaN** [comment]
** На светлое будущее **

- [ ] - диапазоны вместо перечислений подряд идущих значений
- [ ] - форматирование нескольких вложенных скобок в регулярках через контроль размера скобок
- [ ] - слияние переходов, имеющих одинаковые начала и концы, в переходы с длинными метками (исключая эпсилон-переходы такого рода)
- [ ] - возможность модерировать легенду стилей метаданными (т.е. сопоставлять определённому стилю определённый цвет заранее)
- [ ] - возможность выделять кластеры (это ещё надо подумать, какими средствами в `tikz`)
- [ ] - более округлые петли (использование компасных директив типа `nw:ne` в графвизе лагает, в tikz работает лучше)
- [ ] - протестировать, что там получается при использовании библиотеки автоматов в `tikz` (с длинными метками это работать не будет, с короткими - возможно будет)

Не в шапке, чтобы не пугать себя объёмом TODO.

**Comment by TonitaN** [comment]
При автозуме вариант корректного размещения на слайде логично писать в комментарии к Latex - исходнику с диаграммой либо ещё как-то дополнительно (не сразу в include). Т.к. если диаграмму можно вписать в министраницу, то ещё нужно проверить, а впишется ли в министраницу соседняя с ней, а если переносить на сдедующий слайд, то это нужно делать вместе с поясняющим текстом. По комментариям + шаблону уже возможно построить окончательный вариант размещения.

**Comment by TonitaN** [comment]
Читаем `pagedata` --- сколько процентов от ширины и высоты фрейма сжирается по умолчанию (например, `50 ; 80`). В итоговом исходнике первой строкой --- комментарий, в котором указано, можно ли пользоваться дефолтным размещением автомата по горизонтали и по вертикали, и какой процент от рассчитанного размещения (дефолтного или сброшенного) приблизительно будет занимать диаграмма. Чтобы этот процент можно было использовать как входные данные для соседней с ней диаграммы.
Т.к. часто диаграммы очень растянутые, и две нормально помещаются на одном фрейме, но друг под другом и с большим уменьшением. Если они компактные, то адекватное размещение подразумевает министраницу. Если одна компактная, а другая длинная - вот в этом случае получается фигня, но она так или иначе получится.

**Comment by TonitaN** [comment]
Какая-то случайная последовательность автоматов с очень длинными и очень широкими и с небольшими:
```
R = {(a|b)(ba|aab|bc)*(ab|cb)(ca|aab|bca)*(a|)} !!
A4 = MergeBisim.Antimirov R !!
A5 = Minimize.Determinize.RemEps.Thompson R !!
R2 = {a|ba|aa*} !!
A6 = Reverse.Reverse.Antimirov R2 !!
A7 = Minimize.Determinize.Glushkov R2 !!
```
Результат на `pagedata`: `48; 75`
[DummyTest4875.pdf](https://github.com/StarikTenger/Chipollino/files/10408229/DummyTest4875.pdf)
Результат на `pagedata`: `48; 50`
[DummyTest4850.pdf](https://github.com/StarikTenger/Chipollino/files/10408230/DummyTest4850.pdf)
Результат на `pagedata`: `60; 50`
[DummyTest6050.pdf](https://github.com/StarikTenger/Chipollino/files/10408232/DummyTest6050.pdf)
Результат на `pagedata`: `80; 85`
[DummyTest8085.pdf](https://github.com/StarikTenger/Chipollino/files/10408235/DummyTest8085.pdf)

Первый параметр `pagedata` --- предельно допустимая ширина для вписывания в министраницу. Если он больше 49, то он нагло игнорируется, т.к. две такие параллельные министраницы наверняка не вместятся и поедут. Второй параметр `pagedata` --- сколько места на слайде в высоту максимум должна занимать диаграмма, если она не переносится на новую страницу.
Итоговый векторный тайпсет кажется приемлемым, кроме очень больших в высоту диаграмм, в которых ничего не разобрать даже при максимальном выделении им места на слайде. В случае таких диаграмм спасёт только переход в текстовую форму, который обычно не нужен. Поэтому нормально, если чрезмерно высокая степень переполнения будет вызывать предупреждение, что масштаб нечитаемый. Логгер для логгера )

**Comment by TonitaN** [comment]
Для (не)рабской силы. Расшифровка `pagedata` с точки зрения логов (соответствующие проценты желательно оставить в метаданных - комментарии сразу после `\begin{frame}{имя}` в шаблонах):
1. если часть слайда занимают какие-то пояснения, вычитаем её из второго параметра (процент слайда в длину на диаграмму)
2. если хочется дать возможность разместить два автомата на одном слайде (например, было - стало, или при сравнении), первый или второй параметры `pagedata` (или оба сразу) делаем чуть меньше 50 

А больше чем две диаграммы на слайде вряд ли будут нужны, тем более в кратких логах.

**Comment by TonitaN** [comment]
Про хранящиеся в кэше автоматы: по идее, достаточно сохранить имя `tex`-исходника (после альфа-преобразования и стирания разметки) в логгере языка (???). И дальше при обращении к кэшу просто `\input{cached_diagram_name}`.

**Comment by mathhyyn** [comment]
В архиве нет Preprocess

**Comment by TonitaN** [comment]
Уже теперь должно быть)

**Comment by TonitaN** [comment]
На всякий случай напомню:
- `dot2tex`, который качается `pip`, лагает! Нужно брать исходники из репозитория [тут](https://github.com/kjellmf/dot2tex)
- вспомогательные файлы `Aux_input{i}.data` и `L_input{i}.tex`, а также `Meta_input{i}.data` нужно удалять перед новыми запусками, т.к. на их наличие смотрит `Postprocess`.

От рефал-юникода зависеть вроде как не должно, все образцы читают только ASCII.

**Comment by xtoter** [comment]
Если кто-то вдруг потестить захочет, то воть [тык](https://github.com/StarikTenger/Chipollino/wiki/%D0%97%D0%B0%D0%BF%D1%83%D1%81%D0%BA%D0%B0%D0%B5%D0%BC-%D0%A0%D0%95%D0%A4%D0%90%D0%9B).
Проверили, на данной версии отрабатывает корректно.

**Comment by TonitaN** [comment]
Эдгару привет ) Лабу сдать всё равно придётся.

И ещё немного прекрасного от студентов иу9 по теме дня:
![Refal0](https://user-images.githubusercontent.com/13885019/212418743-5488a95e-8829-4058-8ac8-78390c7474bb.jpg)
![Shrek_Refal](https://user-images.githubusercontent.com/13885019/212418838-19ba6c09-f87e-45a0-ba93-98e97409dec8.jpg)

**Comment by mathhyyn** [comment]
Кстати говоря, [раб](https://github.com/KarumaRey) согласен и уже приступил. (Рефал мы ему уже поставили)
Завтра консультация в 14 в 309ю? а то 1я группа не в курсе)))

**Comment by TonitaN** [comment]
В 14 в 330.

**Comment by TonitaN** [comment]
> Кстати говоря, [(не)раб](https://github.com/KarumaRey) согласен и уже приступил. (Рефал мы ему уже поставили) Завтра консультация в 14 в 309ю? а то 1я группа не в курсе)))
> 
> EDIT: да.

Тогда зону обновлений рефал-рендера логично переместить в нерабский репозиторий, т.к. там будет более актуально согласование с рендерингом (эх, кто бы ещё ревьюил рефал-код? @xtoter , не хотите попробовать?). Но шаблон для тайпчекера у меня первый приоритет, когда закончу с лабами и РК (и его тоже с рефалом придётся согласовать из-за таблиц, поэтому пока что на плантацию не переезжаю).

**Comment by mathhyyn** [comment]
Если подразумеваются коммиты, то не возражаем. а если только issue, то лучше остаться в этом репозитории, чтобы все оставалось в одном месте.
я максимум могу только тестить как работает.....
(второй репозиторий(fork) был создан, чтобы не давать лишних прав не участникам проекта)

**Comment by TonitaN** [comment]
Если оперативно что-то фиксить и согласовывать, то удобнее коммитами, т.к. всё время сидеть в EDITах - это конечно наше всё, но рефал github не считает нормальными файлами, и аттачить его приходится через стиль девятки (ака `.pdf.doc.pdf`). Но пока рано об этом, решим, когда перейдём непосредственно к генерации.

**Comment by TonitaN** [comment]
Я тут почитала wiki и поняла, что если пока остаётся рефал, то нужен скрипт, который бы взял на себя часть технических моментов. Для эстетов можно сделать в докере вместе со сборкой основной части проекта )))
А именно, что нам нужно:
1. Скачивание и настройка рефала
2. Сборка рефал-скриптов
3. Скачивание и сетап dot2tex (причём если dot2tex уже есть более старой версии, то нужно выдать предупреждение, что придётся его снести, и отказаться от дальнейшей установки)
Кстати вот latex не обязательно устанавливать, т.к. результатом работы логгера является `tex`-исходник, а его автоматическая трансляция в pdf - уже приятное дополнение.

Если никому не будет охота, постараюсь скрипт или докерфайл хотя бы для внутреннего пользования сделать ближе к релизу. Но обещать не могу, есть и другие задачи (

**Comment by xtoter** [comment]
Ой, я бы взял🙃

**Comment by TonitaN** [comment]
Ок, берите, будет +2 балла ))

**Comment by TonitaN** [comment]
Только рефал, видимо, правильнее конкретно для установки под линукс брать для архитектуры x64, - тот, с которым вы работали на практике. В версии 2008 года поддерживается только архитектура x32, насколько я понимаю.

**Comment by xtoter** [comment]
Ну тут неясен вопрос что по лицензиям, правам и вообще, ибо 2008 года открыто публиковался (может взять любой желающий), а вот х64 я конечно вижу где взять (и вообще много его версий в одном месте вижу, хоть и видеть не должен), но все-таки прав на него у меня нету, и насколько хорошо его указывать в проекте и вообще куда-то выкладывать вопрос открытый(не знаю как там принято в сообществе). (Возможно стоит взять вариант Маздайщика, ибо там все красиво на гите, но не пробывал его запускать)

**Comment by TonitaN** [comment]
Есть такая проблема (( Если x32 будет неадекватен, придётся пока взять 5-лямбда (и всё-таки надеюсь, мы с вами дождёмся официального юникод-рефала x64 в ближайшем будущем ^_^).

**Comment by KarumaRey** [comment]
Ошибка при вставке таблицы: 

![image](https://user-images.githubusercontent.com/86801400/212993208-7417350d-466d-43ed-b2bd-62253d188061.png)

![image](https://user-images.githubusercontent.com/86801400/212993395-bb152bcd-ef2c-46fa-8d25-0cd61d363e38.png)

(В моём репозитории: ветка refal)

**Comment by TonitaN** [comment]
В заголовке tex есть две следующие строки?
```
\PassOptionsToPackage{table}{xcolor}
...
\definecolor{HeaderColor}{rgb}{0.85,.86,0.95} % или любой другой RGB
```

**Comment by TonitaN** [comment]
Для `xcolor` должен быть либо подключён `xcolor`, либо так:
```
\usepackage{graphicx}
\usepackage{color}
```
(пакет `graphicx` подгружает `xcolor`, и если он подключён, то при подключении `xcolor` непосредственно может быть ошибка, поэтому я в преамбуле использую хак с передачей дополнительного параметра `table`)

**Comment by KarumaRey** [comment]
![image](https://user-images.githubusercontent.com/86801400/212998889-4b464373-967a-4359-bbc2-77bf646a2ec2.png)

**Comment by TonitaN** [comment]
> Ошибка при вставке таблицы:
> 
> ![image](https://user-images.githubusercontent.com/86801400/212993208-7417350d-466d-43ed-b2bd-62253d188061.png)
> 
> ![image](https://user-images.githubusercontent.com/86801400/212993395-bb152bcd-ef2c-46fa-8d25-0cd61d363e38.png)
> 
> (В моём репозитории: ветка refal)

А где там эта ветка? 👀 Мне не видно.

**Comment by KarumaRey** [comment]
добавил

**Comment by TonitaN** [comment]
Предлагаю всю математическую разметку делать с помощью рефала пока что: 
- будет единообразно
- будет удобно считать по базовому представлению размеры формул и прочего, для масштабирования (с разметкой придётся её снимать специально для этих расчётов)
- рефалом всё равно логично просматривать весь исходник для задач масштабирования - не сильно замедлит дело ещё переписывание базовых формул по ходу дела

**Comment by mathhyyn** [comment]
> добавить раскраску узлов по группам из метаданных и порождение необходимых цветов с помощью xcolor

как должны эти метаданные выглядеть и где должны находиться?

**Comment by TonitaN** [comment]
Они в dot-файле, после описания узла или стрелки, выглядят как комментарии: `/*'group'[ID]*/`. [ID] любое слово непустое, может быть общим у узлов и стрелок. По каждому id порождается свой цвет. Перед group и после открывающего значка комментария может стоять ещё что-нибудь, но пока что оно не учитывается.

**Comment by mathhyyn** [comment]
хм, тогда автоматы будут доставаться не из кэша
N = MergeBisim.Glushkov {a*a}

(в MergeBisim автомат "до" будет отличаться от выходного после Glushkov из-за раскрашенных состояний)

**Comment by TonitaN** [comment]
Да, по идее в кеш не надо класть раскрашенные. А вроде пока нигде ничего не раскрашивается?

**Comment by mathhyyn** [comment]
> Да, по идее в кеш не надо класть раскрашенные. А вроде пока нигде ничего не раскрашивается?

Нет((

**Comment by TonitaN** [comment]
Если думать, как это сделать в `AutomatonToImage`, возможно, ему стоит передавать множества выделенных в группы состояний отдельным параметром. Это сильно проще, чем рефакторить структуру автомата, чтобы она хранила ещё метаданные. В принципе, стрелки тоже раскрашиваются рендерером, но их множества передавать будет уже не так удобно.

**Comment by xendalm** [comment]
Поддерживаю. Лучше сделать для `AutomatonToImage` свой условный to_txt с параметрами, чем каждый раз создавать раскрашенные копии автоматов только для отображения.

**Comment by TonitaN** [comment]
Ну в общем да.
- dot2tex - дорого
- прогнать ещё разок через рефал с метаданными - дёшево (и более того, уже сделано, нужно только добавить спецрежим только для раскраски).
dot2tex и так без метаданных работает. Так что логично не рендерить прямо всё сразу под каждый случай, а хранить заготовки, которые модифицируются актуальными метаданными. Альфа-преобразование всяких длинных меток тогда тоже впишется идеально, как один из видов рендеринга.

**Comment by TonitaN** [comment]
Кэш + наложение цветов =) (спасибо вектору)

[rendered_report.pdf](https://github.com/StarikTenger/Chipollino/files/10846091/rendered_report.pdf)
