### ISSUE TITLE
Рендер длинных таблиц и формул

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#227]
Та же тема, что у автоматных меток и диаграмм. Сейчас пока что это тот минимум рендера, который нужен, чтобы потом всё собрать в +- адекватные логи.
- [x] - первый по счёту слайд для презентации операции имеет заголовок, на который уменьшается его высота
- [x] - очень желательно (но неохота): индексы считать с меньшим весом, чтобы они не так сбивали расчёт по ширине
- [ ] - сделать наконец министраницы с комментариями параллельно диаграммам
- [x] - адекватное распознавание чисел не в индексах (вот за что рефал - ван лав, так это за его способность разделываться со странными синтаксисами, где одно и то же может означать много разного)
- [x] - нулевой пункт: документация (для внутреннего использования) по функциям встраивания 
- [x] - рассчитать ширину и высоту ячейки таблицы или формулы (подогнать формулу исходя из числа разных символов, чтобы никаких обращений к `preview`, оно тормозит) 
- [x] - сделать перенос слишком длинных строк (связано и так, и обратно с предыдущим пунктом)
- [x] - сделать перенос таблицы на следующий слайд и размещение таблиц в министраницах (применить ту же технику, что для диаграмм, не должно быть сложно, если нормально сделать 1 пункт).

(Но сначала шаблон для логгера...)

**Comment by TonitaN** [comment]
Для логгирования Ардена нужен ещё рендер системы уравнений, если по-хорошему. Но пока подождём самого Ардена, тем более это почти даром получится из рендера формул и таблиц, если не слишком накосячить.

**Comment by TonitaN** [comment]
Наверное, это имеет смысл делать в рендеринге следующим. А ещё нулевым пунктом объяснить, какие фишки встраивания объектов средствами теха используются в рендерерах, чтобы это не выглядело как не пойми откуда взявшийся код.

**Comment by TonitaN** [comment]
### Средства форматирования `tex`-исходников : логи тайпчекера

1. Дерево вычислений: библиотека `dirtree` (проверьте, что подключена). Настраиваемые параметры: `setlength`, `DTsetlength` (не думаю, что у кого-нибудь будет время сейчас в них ковыряться). Начинается так: `\dirtree{%` (обязательно с процентом, т.е. пустым комментарием в первой строчке - не надо пытаться понять КЗ-синтаксис латеха). Кончается просто фигурной скобкой. Синтаксис дерева: `[точка][номер]_[заголовок] [точка]`. Здесь `_` -- пробел. Номера должны быть упорядочены по возрастанию относительно первого вхождения, т.е. вот так нельзя:
```
\dirtree{%
.2 IlieYu N
.1 Arden.IlieYu N
}
```
Плюс-минус номера вложенности соответствуют индексу вложенности в тайпчекере (но порядок вывода чуть-чуть изменён). Лучше погрузить `\dirtree` внутрь широкой министраницы, иначе в некоторых случаях дерево пытается строиться по ширине (магию авторазмещения в латехе тоже не надо пытаться понимать, её можно только принять).

2. Макрос каждого простого типа имеет имя `\[имя в интерпретаторе]TYPE`. Пары (т.е. типы многоместных функций и предикатов) загоняются в макрос `\pair{[аргумент1]}{[аргумент2]}`. Значок `имеет тип`: `\TypeIs`. Регулярка в аргументе загоняется в макрос `\regexparg` (создаёт фигурные скобки чуть большего размера вокруг регулярки); макрос `\regexpstr` при этом тоже нужно применять. Имена переменных загоняются в макрос `\var`. Иконки имеют необязательный аргумент масштаб, поэтому в стандартном масштабе вызываются так: `\[имя иконки]{}`.

**Comment by TonitaN** [comment]
### Средства форматирования `tex`-исходников: рендер автоматов

1. Масштабирование по странице:
```
\adjustbox{max width=\textwidth, min width=0.3\textwidth, max height=0.75\textheight}{
...
}
```
Параметры достаточно самодокументированы. Положим, у нас есть совсем маленький автомат, который получил комментарий (в первой строчке в файле `R_inputX.tex`): `Width percent 34 ; Height percent 14`. Это означает, что его естественный масштаб занимает такой процент от желаемого размещения на странице. Можно передавать эти аргументы в `adjustbox`, чтобы гарантировать, что диаграмма не займёт больше места, чем рассчитанное на неё. Например, так:
```
\adjustbox{max width=0.34\textwidth, min width=0.3\textwidth, max height=0.14\textheight}{
...
}
```
Ну или дать "чуть больше воздуха", добавив, например, 1% .

2. Длинные метки загоняются в `array`. Для этого они разбиваются максимум на 5 строк по разделителю и все, кроме одной строки, вытаскиваются из исходника `dot` перед вызовом `dot2tex` (иначе от их длины посчитается размер узла, и будут огромные пустые состояния автомата). После вызова `dot2tex` метки-плейсхолдеры заменяются на таблицы, сохранённые в `aux`- файлах.

3. Метки `Linearize` делаются полупрозрачными через настройку `\pgfsetfillopacity{0.6}`, которое затем возвращается в норму посредством `\pgfsetfillopacity{1}`. Метки `Annote` остаются без прозрачности. Предполагается, что каждая метка --- это последовательность цифр, которая предварена отметкой о её типе (линеаризация или детерминизация). Отметки типов в принципе можно менять через смену рефальских константных функций `IndicesAlphabet`, `LinearizeSym`, `AnnoteSym`. Если символ войдёт в коллизию с уже используемым другим (кроме запятой, коллизия с которой предусмотрена с учётом того, что цифры предполагаются встречающимися только в индексах), то работать разметка может неверно.

**Comment by TonitaN** [comment]
Посмотрела происходящее в ветке у Дани+Васи. По трудоёмкости это где-то 1-2 человеко-ночи рефала до полностью готовой версии по этим шаблончикам (с учётом размещения). То есть я сейчас ориентируюсь на следующий план. Беру за базу готовый tex-исходник как есть (но регулярки без разметки, чтобы было проще их анализировать), рендерю его рефалом повторно (чтобы подсчитать, как и что размещать на слайдах), и сохраняю в новый tex-исходник. Кастомизация, т.е. объекты для размещения, будет рефалом распознаваться по комментарию `%template_нечто`. Всё, что перечисляется через запятую, буду считать пока что множествами. 

Считаем, что делаем прототип. Если что, это потом успеется переделать не на рефале.

**Comment by TonitaN** [comment]
Разделители, после которых режется формула для переноса:
- запятая не перед цифрой (потому что перед цифрой это указание на разметку, и резать такое не надо)
- альтернатива
- закрывающая скобка или звёздочка не перед закрывающей скобкой или звёздочкой
- пробел
- фигурная закрывающая скобка (такие тоже есть в некоторых логах)

Если нормального разделителя в области видимости не нашлось, режем как попало (ну это уж что-то совсем патологическое с 100500 звёздочек, скобок или разметок подряд). Множество разделителей и их не-follow символов можно настроить кастомно через соответствующую константную функцию. 
```
Separators {
 = (','(NotBefore <Numbers>))
   (')'(NotBefore ')*'))
   ('|'(NotBefore ))
   ('}'(NotBefore ))
   ('*'(NotBefore '*)'));
}
```
Пока что считается, что длина разделителя строго один символ. Надо будет - не проблема поменять, с рефал-стилем-то.

**Comment by TonitaN** [comment]
Принимаем оптимистичную гипотезу, что теорию рендерить и разбивать на подстроки не надо. Проблема в том, что высоту теории в юникоде (длину текста) не очень понятно как рассчитывать автоматически из-за плохой совместимости кодировок, но попробуем пока так. Достаточно сложно устроенную теорию (таблицы, вычурные формулы и диаграммы) не надо смешивать с практикой на одном фрейме, иначе разметку её высоты придётся делать вручную (и причём кому-нибудь другому). Если %begin_theory появляется между фреймами, то всё попадающее в область действия этого  мета-тега не рендерится (считается, что %end_theory в этом случае тоже будет между фреймами, а если нет, всё аварийно упадёт).

**Comment by TonitaN** [comment]
Всё, что не помечено как теория, считается преамбулой к соответствующему объекту, помещаемому в шаблончик. Т.е. переносится на следующий слайд или внутрь министраницы вместе с этим объектом, чтобы не было так:
```
Автомат до преобразования:
[разрыв страницы, новый фрейм]
Собственно автомат
```

**Comment by TonitaN** [comment]
Пока размещаю на министраницах только по одному объекту. В принципе надо столько, сколько влезет по высоте. Но не на пре-альфа.

(спустя 500 строк рефала скоро уже тестирование и дебаг...)

**Comment by TonitaN** [comment]
Ну вот так выглядит авторазбиение, если появляются очень длинные формулы (на один и тот же автомат и таблицу не в тему лучше не обращать внимания, это тестовое).

[rendered_report.pdf](https://github.com/StarikTenger/Chipollino/files/10496353/rendered_report.pdf)

**Comment by TonitaN** [comment]
Это уже почти эстетично:

[rendered_report.pdf](https://github.com/StarikTenger/Chipollino/files/10501504/rendered_report.pdf)

**Comment by TonitaN** [comment]
Иногда есть баги с переполнениями, потому что переизобретаем мини-мини-латех. Но ради скорости работы рендеринга чего не сделать... (потом доладим)

[rendered_report.pdf](https://github.com/StarikTenger/Chipollino/files/10501977/rendered_report.pdf)

**Comment by mathhyyn** [comment]
автоматы пока не должны переноситься на новый слайд?
![image](https://user-images.githubusercontent.com/79749959/214681800-1863dc36-3a2c-42f2-901a-3d8a2a3e4a05.png)

**Comment by TonitaN** [comment]
Иногда переполнения бывают, в основном не с автоматами, а из-за того что неточно подсчитывается длина строк. Сейчас борюсь с ними и с длинными ячейками в таблицах.
