### ISSUE TITLE
Докер (и по хорошему скрипты)

### ISSUE THREAD

**Issue by xtoter** [StarikTenger/Chipollino#229]
Именно, что нам нужно:
1. Скачивание и настройка рефала
2. Сборка рефал-скриптов
3. Скачивание и сетап dot2tex (причём если dot2tex уже есть более старой версии, то нужно выдать предупреждение, что придётся его снести, и отказаться от дальнейшей установки)
Кстати вот latex не обязательно устанавливать, т.к. результатом работы логгера является `tex`-исходник, а его автоматическая трансляция в pdf - уже приятное дополнение.

Если никому не будет охота, постараюсь скрипт или докерфайл хотя бы для внутреннего пользования сделать ближе к релизу. Но обещать не могу, есть и другие задачи (

_Originally posted by @TonitaN in https://github.com/StarikTenger/Chipollino/issues/222#issuecomment-1382631343_

**Comment by TonitaN** [comment]
До экзамена по БД чтобы я никого из Чиполлино за активностью в проекте не наблюдала Хватило функана :(

**Comment by TonitaN** [comment]
Оффтоп: преобразование из разметки tex в html похоже на гомоморфизм (¬‿¬). Только, возможно, потом отдельно расчёт переполнений придётся сделать. Но если нужны продвинутые диаграммы для интерактива с пользователем (и при этом не слишком в форме спагетти), то их, конечно, гомоморфизмом не сделать, это отдельная история, достойная курсача.

Никто же не обязан превращать текстовый исходник в pdf. Его можно потом ещё во что-то конвертировать, и все эти скрипты рендера текстовика (без запуска всяких специфических dot2tex) по своей логике работают быстро. Так что по идее можно иметь в виду оба представления, и если Эдгар захочет рендер в html, это не должно быть уж страшной проблемой ~особенно не на плюсах~.

**Comment by xtoter** [comment]
@TonitaN извиняюсь за плохие вопросы, но вопросик есть, я конечно не юзер окон, так что может меня просветят, ну помимо того, что мало что консольное есть из приложений встроенных (ну файл качается косвенно через bitsadmin, tar только в 10 винде появился ... ) я встретился с проблемой. 
У нас в винде make для сборки Рефала который юзался(и в файлах рефала вроде под него заточено) make из VS.
А VS громоздкий и только консолью не поставишь...
Боюсь не все пакеты вообще смогу консолью поставить ...
Вместо make VS (который еще и только в определенной консоли работает) мы можем взять другой (по крайней мере попробовать), либо туда скачать сразу собранные exe (надо еще найти где взять) 

P.S. Возможно стоит оставить установку пакетов на пользователе (Для windows), а скриптами упростить сборку, и запуск.

**Comment by TonitaN** [comment]
У вас какие окна? И почему нельзя сделать сборку под g++? Я вотпрямщас у Чиполлино не пробовала, но вообще стандартно приходится так и делать для некоторых лаб по тфя, если линукса нет под рукой (как сейчас). У Чиполлино, правда, всё сложнее из-за модульности, так что не уверена, что это удастся до 6 часов утра.

**Comment by TonitaN** [comment]
В файлах рефала вообще нет привязки к плюсовому коду - берётся dot, для него вызывается только dot2tex и рефал )

**Comment by xtoter** [comment]
Ну рефал то тоже ставить надо..., и плюсы (ну с этим проблем нет), и кучу сопутствующего. (В линуксе у меня скрипт сам ставит все необходимые пакеты)
<details>
  <summary>P.S. окон у меня нет, но есть большая идея ...</summary>

![image](https://user-images.githubusercontent.com/76103754/213328822-684e41fb-6a8f-4382-b41c-b1dd2db64521.png)


  
</details>

**Comment by TonitaN** [comment]
Вариант использования git bash не подходит?

**Comment by xtoter** [comment]
Ну там же нет пакетного менеджера ... (мы можем поставит chocolatey и использовать его даже без git bash, но это будет странно для конечного пользователя), ну стоит у него компилятор, ну поставим еще парочку, лишним же не будет?

Ну пример стоит nmake (встроен в VS), но работает он только в powershell для VS, ну поставим еще один make через chocolate, прекольно же!
У меня просто это как у человека с линуксом дисонанс вызывает, зачем 2 штуки которые делают одно и то-же.

**Comment by TonitaN** [comment]
Вынепонимаете, это затем чтобы проверять все лабы по тфя (часто без поллитра кофе не разберёшься, какой компилятор или какая сборка нормально отработает на этих лабах) ) Ну ок, идите спать, пусть это останется на компромат ;) Можно тупо проверить, если есть подходящий make и mingw хотя бы, а если их нет, написать: сорри, кто же сейчас сидит под виндой, мы вам сочувствуем.

**Comment by xtoter** [comment]
О, а вот про gcc поразмышляю, звучит как компромисс ...

**Comment by TonitaN** [comment]
Мне кажется, можно делать тут PR, не дожидаясь гармонизации с виндой. Хотя задача неплохая, но в контексте конференции она не так важна (в отличие от линукса + докера).
