### ISSUE TITLE
Ошибка при subset

### ISSUE THREAD

**Issue by KarumaRey** [StarikTenger/Chipollino#231]
Нашёл проблемный вариант теста.  На тесте с сабсетом, а именно: 

```
Subset {(((a*(((((|(ab)(b)a)b)*b(|(|(||||(((|||a)))))))))))*)} {|b*}
```

выполняется аварийная остановка. 

[Прилагаю log](https://github.com/StarikTenger/Chipollino/files/10435547/log.txt)

**Comment by xendalm** [comment]
Какой приятный минимальный тест: `Subset {a*} {b}`
:)

**Comment by xendalm** [comment]
@shevchenkokk 
`determinize()` не "детерминирует" (добавляет ловушку) автоматам из одного состояния. Из-за этого в `intersection()` цикл не находит нужный переход по символу из объединенного алфавита.

![image](https://user-images.githubusercontent.com/35781938/213012056-003e3572-aa4b-4ae3-b03c-8a74a2c79933.png)
![image](https://user-images.githubusercontent.com/35781938/213012104-27b9d3f9-40b6-45b3-a3b8-bac6377cedb4.png)

**Comment by TonitaN** [comment]
Там более глобальная фишка. При пересечении двух автоматов у них могут быть разные алфавиты, что не учитывалось. И здесь у одного из них и не должно было быть ловушки, потому что в алфавите из буквы `a` её нет у автомата для `a*`. Так что надо проверять алфавиты и с учётом этого уже ловушки.

**Comment by xendalm** [comment]
Как это все нужно будет менять, когда добавятся флаги это уже другой вопрос...

**Comment by TonitaN** [comment]
Так, вот теперь мне интересно, что будет в функции сравнения, если автоматы уже считаются детерминированными? Там тоже происходит их "передетерминизация" с учётом обновлённого алфавита? (лень смотреть код, быстрее спросить у боцмана)

**Comment by xendalm** [comment]
Буквальное сравнения я писал без этих фокусов. Там сразу будет False в случае разных алфавитов

**Comment by TonitaN** [comment]
Нет, не в буквальном, в проверке эквивалентности.

**Comment by xendalm** [comment]
А из эквивалентности вызывается буквальное для минимальных, поэтому вроде как не должно ничего объединяться

**Comment by TonitaN** [comment]
Понятно, значит, вопрос остаётся только насчёт `Subset`.

**Comment by TonitaN** [comment]
Вопросов нет - по коду видно, в чём проблема. Точнее, один вопрос всё-таки есть: почему этот код там появился и что он чинил)
