### ISSUE TITLE
Баг генератора

### ISSUE THREAD

**Issue by KarumaRey** [StarikTenger/Chipollino#233]
```
N3 = States.PGtoNFA.PrefixGrammar.DeLinearize.PGtoNFA !!
```

Нет аргумента, а он, судя по всему, нужен, потому что в таком виде не работает.

![image](https://user-images.githubusercontent.com/86801400/212998022-aafedd99-58e0-4825-a906-ff590e342e4c.png)

**Comment by xtoter** [comment]
Я так полагаю у нас новый тестер🙃 (там моноид лежит ...)
