### ISSUE TITLE
UPD. Ночь с   л̶̶̶о̶̶̶г̶̶̶г̶̶̶е̶̶̶р̶̶̶о̶̶̶м̶̶̶ ̶ч̶и̶п̶о̶л̶л̶и̶н̶о̶ ̶ ̶ ̶ ̶̶̶1̶̶̶ ̶ ̶2̶  экзаменом

### ISSUE THREAD

**Issue by xtoter** [StarikTenger/Chipollino#234]
Пытаемся за ночь  ̶п̶о̶л̶у̶ч̶и̶т̶ь̶ ̶д̶о̶п̶у̶с̶к̶ исправить и написать все что надо и не надо.
<details>
  <summary>Spoiler</summary>
  
![image](https://user-images.githubusercontent.com/76103754/213008903-9b9f9102-b77a-4360-962f-170365ef6b91.png)

  
</details>
<details>
  <summary>UPD.</summary>
  
Их становится больше...
![y2k8c-UWEw3qJJd85b1gkqhDpcmCIvgzii9UlYSQQEoxFUn8rgJjOG-GkyfednDVjZ3z6Q8cS9r0rdEO5JZa0g3r](https://user-images.githubusercontent.com/76103754/213024173-8b6ff677-5531-4ec3-a755-8856ea1567aa.jpg)

  
</details>

**Comment by TonitaN** [comment]
Консилиум решил, что без парсера размеченных выражений внутреннего представления не получится сделать `Normalize`? 👀

**Comment by xtoter** [comment]
>  eyes

Так вроде только-только доделали🙃

**Comment by dak151449** [comment]
Вообще-то 2 часа назад)

**Comment by xendalm** [comment]
Парсер подразумевался для полноты картины и всяческих экспериментов. Что там с Normalize, не знаем)

**Comment by TonitaN** [comment]
Эээ! Это уже запрещённый приём в EDIT-ах! А то кто-нибудь поменяет рефал-скрипты рендера, а я и не замечу )

**Comment by xtoter** [comment]
больше сегодня не буду( 💀💀💀

**Comment by TonitaN** [comment]
> парсер используется в ардене и disambiguate, к-е из-за этого падали после линеаризации. 

Да. Это было средство выявления рефал-стиля. Но теперь уже назад дороги нет, граница всё равно преступлена...

**Comment by mathhyyn** [comment]
> > парсер используется в ардене и disambiguate, к-е из-за этого падали после линеаризации.
> 
> Да. Это было средство выявления рефал-стиля. Но теперь уже назад дороги нет, граница всё равно преступлена...

оно обязательно исправится...((((

**Comment by xtoter** [comment]
Я кстати напомню о недочете
<details>
  <summary>Падал прошлогодний снег</summary>
  
У нас в Tex, сгенерированном pdf, копирайте и т.д. указан 2022г.
Если про копирайт понятно что там вручную, то в отчете можно вставлять текущий год системы (год при генерации).
  
![image](https://user-images.githubusercontent.com/76103754/213031287-67e2e150-6670-45f6-87f0-f3011e1243df.png)
Возможно в будущем стоит писать еще версию сборки (пригодится при конфликтах всяких, можно быстро глянуть где свежесгенерированный тот или иной автомат к примеру ... )
</details>

**Comment by TonitaN** [comment]
В отчёте у нас ещё "лучшая команда разработчиков по ТФЯ", которую я добавила для камерного использования, т.к. авторство нужно было. Оставляем этот анонс для публики? Он накладывает на нас всех определённые обязательства %)

**Comment by xtoter** [comment]
А что, не лучшая?

**Comment by TonitaN** [comment]
На ИУ9 (и возможно во всём МГТУ) точно лучшая ❤

**Comment by TonitaN** [comment]
Это была месть за EDIT-ы от имени @xendalm , но я исправила.

**Comment by xtoter** [comment]
Дедлайн в 6 утра все ближе, бойцы сдаются, цели не достигнуты, становится страшно!
<details>
  <summary>spoiler</summary>
  
![image](https://user-images.githubusercontent.com/76103754/213070265-c840f11e-a862-4dc2-a7d9-658e8bcb7bd8.png)
не бейте нас ...
  
</details>

**Comment by TonitaN** [comment]
Некий бонус для @xtoter и @Robby-the-paladin (а также @StarikTenger , который в принципе должен в такой ситуации как капитан помочь, но его на групповых фото почему-то нет) - то, что они могут взять направления в расчёте на 28 января, пересдать ТФЯ в Переславле и привезти их в Москву в понедельник или когда вернутся.

**Comment by TonitaN** [comment]
@KarumaRey , какое у вас ТЗ от ~госпожи~ @mathhyyn ? Т.е. что требуется как результат вашей работы?

**Comment by mathhyyn** [comment]
> @KarumaRey , какое у вас ТЗ от ~госпожи~ @mathhyyn ? Т.е. что требуется как результат вашей работы?

Генерация кратких логов ф/й интерпретатора по входу-выходу (уже готово, я одобрила), добавление (автоматическое) в шаблоны тех дополнительных логов, которые выводились раньше (классы эквивалентности, н-р) (вроде доделано, но что-то полегло(( ) 
Авторазмещение автоматов (хотя бы перенос на след слайд), к этому ещё не приступил, но тз выдано (напряжем даже в случае получения зачёта 😈 )
Добавил вывод таблицы после автомата
И ещё несколько мелких поручений

**Comment by TonitaN** [comment]
За героические волевые усилия @xtoter (возникшие в результате неудачного тайм-менеджмента, однако) всё-таки допущу. Но с вооот таким компроматом, который ещё дособеру сегодня ночью.

**Comment by TonitaN** [comment]
@dak151449 просто герой (как и вы, @mathhyyn ) - выручил в критической ситуации. Я тут подумала - если капитан сегодня опять ничего не скажет, сама разберусь с дополнительными 13 баллами, сколько наёмной силе, а сколько вам (и кому).
А вот насчёт наёмной силы ещё посмотреть по допуску надо. Ну нет у нас рычагов влияния, кроме н/а - вон на @Robby-the-paladin даже н/а не подействовало...

**Comment by StarikTenger** [comment]
Распределение:
Саша + 6
 Вася + 4
Алина +1
Кирилл +2

**Comment by xtoter** [comment]
<details>
  <summary>Часть 2     ̶о̶т̶ч̶а̶я̶н̶и̶е̶</summary>
  
![image](https://user-images.githubusercontent.com/76103754/213305597-be8c70a1-acfc-497d-bd0d-88e11febb42a.png)


  
</details>

**Comment by TonitaN** [comment]
@mathhyyn , вам-то что не спится? Или присматриваете за наёмной силой?

**Comment by mathhyyn** [comment]
> @mathhyyn , вам-то что не спится? Или присматриваете за наёмной силой?

Вечерний сон - наше все
А наемная сила занята бд((

**Comment by TonitaN** [comment]
Ух ты, а я и не задумывалась, что в коммите можно сослаться на чужую страницу.

**Comment by TonitaN** [comment]
@mathhyyn , вопрос к вам. Считаете ли вы, что ваш наёмный персонал может быть допущен? Они (почти никогда) не доделывают без угрозы долгов, проверено :(

**Comment by mathhyyn** [comment]
> @mathhyyn , вопрос к вам. Считаете ли вы, что ваш наёмный персонал может быть допущен? Они (почти никогда) не доделывают без угрозы долгов, проверено :(

Допуск, считаю, что заслужил.
Он выразил добровольное согласие продолжать помогать нам по проекту, т.к. результат(логирование) еще предстоит доводить до приемлемого вида...

**Comment by TonitaN** [comment]
Ну когда-то и @Robby-the-paladin выразил добровольное желание принять участие в конференции. Вряд ли кто-то его заставлял.

Ок, допустим @KarumaRey . Правда, как он будет что-то сдавать сегодня, если у него БД, непонятно.

**Comment by StarikTenger** [comment]
кто бы мог подумать, что за подробность логов отвечает флаг тайпчекера...

**Comment by StarikTenger** [comment]
Конец.

<details>
  <summary>всё!</summary>

![изображение](https://user-images.githubusercontent.com/48261272/213824692-c697b1e8-eac3-4ee5-bd5d-c911abc4d054.png)

</details>
