### ISSUE TITLE
-2 дня до релиза

### ISSUE THREAD

**Issue by xtoter** [StarikTenger/Chipollino#236]
Подгоняем для релиза, но пока не получается, если можно, то в четверг, чтобы на завтрашнем релизе уже всё было.
Спасибо, что помогаете нам в этом.
<details>
  <summary>Spoiler</summary>
  
![image](https://user-images.githubusercontent.com/76103754/214108641-20861fd6-d67b-43bb-ad20-68c13f37dea5.png)

  
</details>

**Comment by TonitaN** [comment]
В крайнем случае можно и в пятницу, но я бы хотела, чтобы в пятницу уже все отдыхали, и если кто не досдал что-то - тот досдал (а @xendalm готовился). А если закончить к 6 утра 27-го, не очень-то хороший отдых получится.

**Comment by TonitaN** [comment]
Кстати, мы вот тут мучаемся с рендерингом, а в реальных разработках в том же норси народ спокойно делает визуализации с такими переполнениями по вертикалям и горизонталям, которые нам в страшном сне приснятся, и им нормально. 

Поэтому повторю главный тезис: не надо себя недооценивать, вы крутые, но совершенству нет предела, а мы тут беспредельщики.

**Comment by TonitaN** [comment]
Пустые автоматы не надо отправлять на рендер, иначе будет баг (в них нет `dummy`-состояния).

**Comment by xendalm** [comment]
Возник вопрос насчёт пустого автомата. Понятно, что иногда полезно видеть на выходе функций пустоту. Но вот если мы сейчас передаём такой на вход возникают ошибки, как уже было замечено. И проблема в том, что для всех функций будет своя обработка этого случая. Можем ли мы просто запретить передавать пустые автоматы на вход?

**Comment by TonitaN** [comment]
Что-то странное обнаружилось при порождении базовых логов с разметкой (которые были раньше):
```
	linearised regex:

	a.0a.1*|a.2*a.3|a.4*a.5%template_linearised regex

	first:

	a.01 a.23 a.34 a.45 a.56 %template_first

	end:

	a.12 a.01 a.34 a.56 %template_end

	pairs:

	a.01a.12 a.12a.12 a.23a.23 a.23a.34 a.45a.45 a.45a.56 %template_pairs
```
Откуда двойные индексы у букв в множествах?

**Comment by TonitaN** [comment]
Так, ну логи у нас очень интересные пока что ) Таблицу легенды (которая `L_input`) надо обязательно привязывать к автомату, к которому она относится, иначе она вставляется в комментарии ко всем автоматам вообще! 

Там, где логи адекватные, результат уже более или менее адекватный. Конечно, нужно в принципе на две колонки делить длинные списки формул, и в министраницы параллельно друг другу вмещать не только диаграммы, но и диаграммы + формулы, например. Но для пре-альфа (и с учётом того, как пока что выглядят предварительные логи для рендеринга) сойдет.

**Comment by mathhyyn** [comment]
> Так, ну логи у нас очень интересные пока что ) Таблицу легенды (которая `L_input`) надо обязательно привязывать к автомату, к которому она относится, иначе она вставляется в комментарии ко всем автоматам вообще! (rm на винде не работает)

как так((
у меня все удаляется...

**Comment by TonitaN** [comment]
мб на линуксе? На винде никак...

**Comment by mathhyyn** [comment]
@xtoter обещал сделать кроссплатформенность через makefile, и в зависимости от ОС будем выбирать какую команду прописывать

**Comment by TonitaN** [comment]
Предлагаю творческую задачу гармонизации с виндой отложить до после всех дедлайнов. Я руками поправлю, а если кто-то другой на винде что-то будет запускать, ну, ему же выразили сочувствие в соответствующем ридми.

**Comment by TonitaN** [comment]
По поводу длинных меток в Антимирове. Не очень здорово, когда за этим автоматом всё время таскается легенда (если её нет, то длинные метки не так и длинны, а значит, вполне читаемы). Преобразование другое, и конкретные производные, да ещё и такие длинные, уже не очень интересны (всегда можно вспомнить, что было вместо них). Есть предложение, если метки очень длинные (в легенду выносятся регулярки с посимвольной длиной >15), делать альфа-преобразование при переходе к следующему шагу преобразований. Тут подумать нужно, как это сделать аккуратно, т.к. в рендеринге переименовываются только уж совсем длинные метки, а здесь наверное логично переименовать вообще все.

**Comment by TonitaN** [comment]
В рабском репозитории пока так и странные индексы в first, end, pairs. Это норма? (в смысле, в него пока исправление не вливалось?)

**Comment by TonitaN** [comment]
Надо поправить очепятки в русском в шаблончиках (автозаменой).

**Comment by TonitaN** [comment]
Что нам нужно:
- дозалить докер и скрипты
- если рефал-нормализация жива, то пора выходить из сумрака
- табличные логи MN и GSh! Я знаю, что там будут большие в ширину таблицы, с которыми придётся маяться уже мне, но надо.
- под вопросом - логгирование тайпчекера. Шаблончик есть, но успею ли подогнать под него вывод - непонятно. Попробуем.

**Comment by TonitaN** [comment]
Какое-то странное `end`-множество:
```
E = Glushkov.Arden.IlieYu {a(b*a)*|a*} !!
```
Результат ещё до рендеринга:
```
b.1 b.1 a.2 b.1 b.1 a.2 a.0 b.1 b.1 a.2 b.1 b.1 a.2 a.0 a.4 b.1 b.1 a.2 b.1 b.1 a.2 a.0 b.1 b.1 a.2 b.1 b.1 a.2 a.0 a.4 a.3 %template_end
```

**Comment by TonitaN** [comment]
Нужен рабский труд: перепроверить, что все объекты, которые вставляются в логи, имеют переносы строк в форме `\\\\`, а не в форме `\n`. Иначе по виду объекта невозможно будет понять, принадлежит ли он "дыре" (т.е. вариативной части) или относится к фиксированным заранее вставленным в шаблон пояснениям. Или придётся ввести теги `begin template` и `end template`, иначе метаграмматика шаблонов станет неоднозначной.

**Comment by TonitaN** [comment]
Таблицы базово логгируем так:
`$\begin{array}{[маркеры столбцов]}` --- первая строчка
`\end{array}$` --- последняя строчка
Остальные строки заканчиваются на `\\\\` (для разбивки по строкам таблицы) и содержат нужное количество `&` (для разбивки по ячейкам). Вертикальные и горизонтальные линии ставить слишком часто не надо: достаточно отделить заголовок. Остальное будет размечено зеброй и по надобности как-нибудь ещё.

**Comment by TonitaN** [comment]
`Test` пока не логгируется?

**Comment by mathhyyn** [comment]
> `Test` пока не логгируется?

Нет, планируем заняться, заодно с таблицами

**Comment by TonitaN** [comment]
Так, вопрос по существу. Когда вы планируете закрывать подготовку к релизу? Ответ 6 утра 27 января не принимается, т.к. у вас уже автобус в Переславль в 8-30 (насколько помню). Я, конечно, примерно так и делала всегда перед отъездом в бауманку (заканчивала проверять лабы в 4 утра и выезжала в 5-30), но вы уверены, что это полезная практика? Отговаривать никого не могу, т.к. сама подаю плохой пример.

Как приедете, я на некоторое время украду у вас @xendalm для подготовки. Потом верну (если никто не захочет тратить время, чтобы его послушать разок, а если кому не жалко минут 40, то будем благодарны, но это уже желательно встретиться повторно, лучше перед отъездом в ИПС). Приедете в город, и можно гулять до вечера, потом варианты добраться в гостиницу - либо такси, либо областной автобус на Нагорье или Новоселье (17 и 17-30 от автостанции, особо ушлые могут поймать его на перекрестке с Подгорной, но при виде вас он вряд ли остановится, т.к. вы слишком похожи на масквичей).

**Comment by mathhyyn** [comment]
15 дня 28 января 😎

**Comment by mathhyyn** [comment]
в целом уже почти можно логгер в main сливать

**Comment by xtoter** [comment]
Да и докер вроде можно 🥺👉👈

**Comment by mathhyyn** [comment]
я вас прерву

можно в mathmode преобразовывать `->` в \rightarrow или самим при передаче логов прописывать?

**Comment by TonitaN** [comment]
Можно.

**Comment by mathhyyn** [comment]
Результат работы верификатора:
![image](https://user-images.githubusercontent.com/79749959/214729328-efb5aabb-b4c2-4488-943b-77c8efa43694.png)

Не знаю как решить небольшую проблему:
после MathMode теряются все пробелы

на таком глупом примере (фигурные скобки еще ладно, можно поменять to_txt для выражения в интерпретаторе)
N = {a}
Verify (Equal N {a})

![image](https://user-images.githubusercontent.com/79749959/214729689-6aa03169-e08c-48ea-ab27-ceea947603bc.png)
![image](https://user-images.githubusercontent.com/79749959/214730187-ce3442bf-2eb6-49b2-99e9-3caeed58049a.png)

**Comment by TonitaN** [comment]
`\Equal\;N\;{a}` В принципе, это можно сделать и автоматически, если в парсере добавить распознаватель имён функций, но можно и логировать сразу с вынужденными пробелами.

**Comment by TonitaN** [comment]
А слияние по бисимуляции и должно быть сильнее, чем follow. В этом смысле всё правильно.
Проверьте, как работает минимизация Брзозовски и удаление эпсилон-правил для Томпсона. Follow получается в принципе так:
deannote(minimize(rmeps(annote(Thompson (R)))))

**Comment by mathhyyn** [comment]
> А слияние по бисимуляции и должно быть сильнее, чем follow. В этом смысле всё правильно. Проверьте, как работает минимизация Брзозовски и удаление эпсилон-правил для Томпсона. Follow получается в принципе так: deannote(minimize(rmeps(annote(Thompson (R)))))

не поняла что нужно сравнивать... но второе явно не похоже на что-то минимальное

```
Equal (Glushkov {a*b*}) (RemEps.Thompson {a*b*})
```

![image](https://user-images.githubusercontent.com/79749959/214735096-2f14dfd1-dfb9-40b6-b62a-d2da6853629e.png)

**Comment by xendalm** [comment]
А ведь оно когда-то работало...

**Comment by TonitaN** [comment]
Разбираюсь по примеру из статьи. У нас слишком долго работает RemEps, если смотреть на производительность.
Жалкая регулярка:
`(a|b)(a*|ba*|b*)*`

**Comment by TonitaN** [comment]
Непонятное что-то происходит. На этой регулярке `RemEps` строит такой автомат с меньше чем 20 состояниями, что его переходы переполняют память у латеха. Сейчас придётся разбираться ещё и с этим.

**Comment by TonitaN** [comment]
Руками всё сходится: действительно после перехода к эпсилон-замыканиям `Thompson {a*b*}` - это `Glushkov {a*b*}`. Что-то мы намудрили с эпсилон-замыканиями, попробую разобраться по коду.

**Comment by TonitaN** [comment]
Так в итоговом автомате там те же состояния, что и в том, который до слияния по эпсилон-замыканиям! В этом и баг. Новые состояния должны быть эпсилон-замкнутыми, а наш `RemEps` просто добавляет к тем состояниям, что были, переходы по эпсилон-замыканиям. Естественно, в результате получается очень много переходов.

**Comment by xendalm** [comment]
Но мы же проверяли эту гипотезу @shevchenkokk... Как я это пропустил(

**Comment by mathhyyn** [comment]
еле нашли проблему:
после mathmode hline у таблицы заворачивался как регулярка
![image](https://user-images.githubusercontent.com/79749959/214743711-b5f17f28-a8e9-494a-a406-5756e991a741.png)

и из-за разметки через точку число 0.001000 выглядит так
![image](https://user-images.githubusercontent.com/79749959/214744107-58c2d191-571a-4a57-a2fa-ce6e02f3b129.png)

**Comment by TonitaN** [comment]
Скиньте рабочий тест, проблемы сейчас исправим (и с заголовками на русском тоже).

**Comment by mathhyyn** [comment]
Любой:
```
Test {a} {a*} 1
```
закомментировали вставку \hline и все собирается
![image](https://user-images.githubusercontent.com/79749959/214748172-29fd1e5b-dd60-4535-902e-613724b2509b.png)

**Comment by TonitaN** [comment]
Теперь `\hline` должно быть можно. И другие теги, которые перечисляются в множестве `TableTags`.

**Comment by mathhyyn** [comment]
![image](https://user-images.githubusercontent.com/79749959/214759926-8220dbcf-9e10-41dd-b944-bb44d67e7a72.png)
интересно, будет ли это кто-то ревьюить?

**Comment by TonitaN** [comment]
Почему-то таблица G-sh выводится в логах терминала при вычислении, а в логах исходника получается так (вместо слов числа):
```
  &32 &97\\\hline
97 & 1 &1\\
32 & 0 &1\\
```

**Comment by TonitaN** [comment]
> ![image](https://user-images.githubusercontent.com/79749959/214759926-8220dbcf-9e10-41dd-b944-bb44d67e7a72.png) интересно, будет ли это кто-то ревьюить?

Да, мне тоже интересно, с учётом 2000 строк рефала в этой ветке особенно ))

**Comment by mathhyyn** [comment]
> Почему-то таблица G-sh выводится в логах терминала при вычислении, а в логах исходника получается так (вместо слов числа):
> 
> ```
>   &32 &97\\\hline
> 97 & 1 &1\\
> 32 & 0 &1\\
> ```

В терминал выводится МН, судя по коду
А с GSh мы не успели разобраться

**Comment by TonitaN** [comment]
С MH всё отлично.

**Comment by TonitaN** [comment]
Так, с логами поработали ударно. Если вы и вправду желаете провести так же жарко и следующую ночь, то планы такие:
- логгер тайпчекера! 
- рабский труд: русификация логов (а то у нас часть комментариев по-английски, часть по-русски)
- тест подключения теории
- тест вложенных логов (и заодно отладить сообщения о кэшировании и т.д.)
(а давайте уже не будем это делать?)

Если следующей ночью планируем спать, то осталось немного (это не отменяется и если спать не будем):
- исправить баг с удалением эпсилон-правил
- перепроверить ещё раз накачку
- протестировать все гипотезы, которые надо
- перепроверить, что генератор использует актуальные функции
- поискать ещё баги в рендеринге и несогласованности в логах

**Comment by TonitaN** [comment]
Если где-то что-то кладётся в кэш впервые, причём явно не вычислялось, тоже надо подходящее место в логах предусмотреть. Сейчас займусь этим, сначала в шаблончиках.

**Comment by xendalm** [comment]
Минимизация по Брзозовски вообще тоже далеко не всегда срабатывает
`a*b*`
![image](https://user-images.githubusercontent.com/35781938/214875828-70531b73-1d9e-4644-b365-0fe49f09e955.png)

**Comment by TonitaN** [comment]
...и наверняка это связано с ситуациями, когда из-за обращения появляются эпсилон-переходы. Что говорит верификатор, какие там контрпримеры?

**Comment by xendalm** [comment]
Вообще каждый второй false выдает
Может я неверную цепочку применяю

![image](https://user-images.githubusercontent.com/35781938/214884619-f3f21824-e1a8-42fe-b843-7673daf6b825.png)

**Comment by TonitaN** [comment]
Нет, цепочка верная. Скорее всего, опять нужно смотреть на слияние состояний в детерминизации (

**Comment by TonitaN** [comment]
Так, в общем, мы выяснили, что теоретикам остро не хватает Чиполлино в организме: они пишут "а", а подразумевают "б". И ни у кого нет верификаторов гипотез, чтобы их на этом поймать. Даже когда они подразумевают что-то правильное, пишут они какую-то фигню:

[HAVE_FUN_WITH_AUTOMATA.pdf](https://github.com/StarikTenger/Chipollino/files/10512215/HAVE_FUN_WITH_AUTOMATA.pdf)

Читаем соответствующую статью на стр.125: указанные в таблице алгоритмы подходят в том числе для простых регулярок. Читаем описание удаления эпсилон-правил: там ни слова о слиянии эпсилон-замыканий в одно состояние ("настоящий математик понял бы")! Так что Томпсон в Глушкова по их же алгоритму никак не превратится: состояний будет разное число. 

Lecture Notes in CS , так-то! Нет, я конечно сама бывало что полную хрень видела, на которую нужно было рецензию с посылом "в избранные" помягче написать, но тут не хрень, всё работает в правильных допущениях, и автор классик (привет мюресы), однако никто из рецензентов ничего не заметил, потому что "ну что мы будем в сотый раз читать про хороши известные нам алгоритмы".

**Comment by TonitaN** [comment]
Сейчас будем разбираться с минимизацией по Брзозовски. О, как же это всё прекрасно 😂

P.S. - Прикол с Глайстером-Шаллитом, усиление которого было несколько лет до него напечатано в том же самом журнале (естественно, на него почти никто не ссылался), мы уже проходили.

**Comment by TonitaN** [comment]
Вопрос к @shevchenkokk : если новый RemoveEps добавить перед вызовом детерминизации, минимизация Брзозовски не начинает работать согласно теореме?
Сейчас тоже скачаю эту ветку и буду проверять.

**Comment by shevchenkokk** [comment]
Там ещё баг обнаружился в новом `remove_eps`. Сейчас чиню.

**Comment by mathhyyn** [comment]
вылезла проблема
попробовала добавить теорию
report:
![image](https://user-images.githubusercontent.com/79749959/214944447-6dca4184-7a6c-4063-bc88-d41d6a9ed5d7.png)

и она просто игнорируется
rendered_report:
![image](https://user-images.githubusercontent.com/79749959/214944375-a7324fda-99f0-43da-a46e-cce0b1c68840.png)

(может к тому, что заключено между `%begin detailed` `%end detailed`, не применять форматирование?)

**Comment by TonitaN** [comment]
Плейсхолдер для теории уже был, провела последнюю настройку, вроде работает, но нужно тестировать.

**Comment by TonitaN** [comment]
В рамках подготовки к докладу и к давней дискуссии "зачем latex, да ещё и слайды". Ну из него потом можно гомоморфно всё что хочется получить, наверное, в этом главный плюс. И само по себе интересно и нестандартно, но это уж на любителя.

Я посмотрела, как наши исходники взаимодействуют с pandoc. Действительно, если через pandoc, то в кое-какую форму html можно наши исходники за человеко-сутки рефала превратить. Если же делать красиво, то можно написать свой мини-pandoc за человеко-неделю рефала, а потом ещё сколько-то настраивать разный дополнительный функционал.
В плюсы по трудозатратам не переводила, потому что не могу объективно оценить на них. На питоне, может, ну чуть дольше чем на рефале выйдет, но тоже вполне обозримо при хорошем владении ТФЯ и техом.

**Comment by mathhyyn** [comment]
![image](https://user-images.githubusercontent.com/79749959/214964057-ccbce648-2843-4ddd-9a3b-4b759a57dc7c.png)
![image](https://user-images.githubusercontent.com/79749959/214964102-a8f26bfc-3bdf-44f6-9f58-2c1c2ffa2afb.png)

**Comment by mathhyyn** [comment]
```
Set log_theory true
N = MergeBisim.Glushkov {(aa|b)*b}
```
чет все сломалось...
![image](https://user-images.githubusercontent.com/79749959/214970182-6efd1ac9-2c0d-4e8a-9863-f8117dd6a565.png)

**Comment by TonitaN** [comment]
Это может быть конфликт enumi и beamer, есть такая тема. Кидайте исходник, где приключилось, сейчас пофиксим.

**Comment by TonitaN** [comment]
Впредь нужно быть аккуратнее с именованием коммитов на английском, однако.

**Comment by mathhyyn** [comment]
да я
![image](https://user-images.githubusercontent.com/79749959/214982461-8edb4e71-cbfa-4291-bffa-cca5731dab76.png)

**Comment by mathhyyn** [comment]
что-то я поторопилась
не работают пары (ф/и где больше одного аргумента)
![image](https://user-images.githubusercontent.com/79749959/214984023-42b5ed49-8c6a-4b64-9c60-46538e7e7333.png)
так же с Test
(для Verify аргументы не прописаны)

**Comment by TonitaN** [comment]
Странно, у меня работает после форматирования. Версия formatter в рефальской рабской ветке вроде бы правильная, за час ночи. Она пересобрана?
[rendered_report.pdf](https://github.com/StarikTenger/Chipollino/files/10514661/rendered_report.pdf)

**Comment by mathhyyn** [comment]
Ой, это последствия моих перебежек между репозиториям
Все отлично

**Comment by TonitaN** [comment]
В TestsApp в main так и должен быть только один тест рефала? Или это случайно получилось?

**Comment by TonitaN** [comment]
Так, а вот теперь про рефал @xendalm в докладе сказать придётся. Изначально я не очень этого хотела, т.к. он появился спонтанно и не от лучшей жизни (хотя, возможно, и не к худшему), но теперь... кажется, это вообще единственный проект, в котором рефал есть в автотестах в мердже! И это само по себе интересно, тем более на конференции по СПО. Там вполне себе знают, что такое рефал, хотя представителей вымирающего вида там особенно нет. Я вообще только троих динозавров знаю, кто пользуется рефалом в чём-то важном для себя (и отличном от написания очередного рефала): двое в Переславле и один недавно ушёл с иу9 :(
Так что придётся @xendalm взять консультацию у @xtoter , пусть поделится опытом, об этом точно будет в тему сказать в докладе.

**Comment by TonitaN** [comment]
Вы бы на память сфоткались перед релизом, пока все вместе там)
Завтра ещё кому-то докладчика запечатлеть надо.

**Comment by dak151449** [comment]
Хотим выразить Вам благодарность от всех луковичек. Удивительно, как из обычной лабораторной работы №2 проект вырос во что-то прикольное и ~~забагованное~~ масштабное. Спасибо за поддержку и за то что организовали нам это прекрасное приключение 🧅

PS: Как вернемся из отпуска будет релиз

<details>
  <summary>Spoiler</summary>

![3 1](https://user-images.githubusercontent.com/77326286/215359671-8d5e3e1b-5a58-40d4-b942-39a422c7726e.png)

![1](https://user-images.githubusercontent.com/77326286/215359614-b8e7c020-291e-4fb0-ab9a-cf2ce5cc30cb.jpg)

![2](https://user-images.githubusercontent.com/77326286/215359618-65de9980-97f5-457f-952c-541bb7fdfee6.jpg)




</details>

**Comment by TonitaN** [comment]
Как же мне нравится наше совместное творчество на курсе ТФЯ )

Bonchi, F. and D. Pous2013.   Checking NFA equivalence with bisimulations up to congruence.   Ine 40th Annual ACMSIGPLAN-SIGACT Symposium on Principles of Programming Languages, POPL ’13, Rome, Italy - Janu-ary 23 - 25, 2013, R. Giacobazzi and R. Cousot, eds., Pp.  457–468. ACM.

Я и не догадывалась про эту статью, когда мы с @xendalm думали над алгоритмом... Впрочем, это уже не первый раз, когда мы уже не велосипед в Чиполлино переизобрели, а кое-что посерьёзнее...

**Comment by TonitaN** [comment]
А теперь попытаемся осознать сделанное:

- демонстрационная функциональность проекта во многом превосходит библиотеку Automata в Python, визуализация значительно превосходит. Что не сделано у нас и сделано там, доделывается несложно.
- функциональность проекта много в чём превосходит и мало в чём уступает библиотеки конечных автоматов в Wolfram, визуализация *несравненно* превосходит.

Страдания по поводу необходимости ставить latex (которой нет, если не транслировать в pdf, а собирать исходник, например, в Overleaf) с лихвой перекрываются преимуществами визуализации. По поводу багов тоже страдать излишне, как показывает опыт. Теперь уже релиз не актуален (т.к. у меня на руках более продвинутая версия, в которой я делаю что хочу и ещё много чего доработаю к новому учебному году), но проект был явно его достоин.

Успехов вам в новом семестре, и ещё раз спасибо за интересную и продуктивную коллаборацию.

**Comment by TonitaN** [comment]
Продолжаем хорошеть. Теперь раскраска и на переходах (и да, я пробовала перемежающийся пунктир, но даже двухцветный он не всегда хорош, а уж если переход попадает в 3+ класса, то получается вообще печаль).

[STEP_slides.pdf](https://github.com/StarikTenger/Chipollino/files/10922434/STEP_slides.pdf)

P.S. - Разбор той самой статьи полностью сделан. Все допущения и умолчания выведены на чистую воду (не так страшны они, как то, что про них ничего не было сказано) :)

**Comment by TonitaN** [comment]
Заработал новый метод определения полиномиальных компонент неоднозначности. Неожиданно в ход пошли трансмоноид и старое удаление эпсилон-правил. Алгоритм пока не оптимален, но работает уже быстрее и гораздо точнее, чем найденные в сети аналоги. На регулярке из примера ниже ломаются вообще все определители неоднозначности, которые удалось найти и запустить. Теперь - кроме нашего.

[rendered_report.pdf](https://github.com/StarikTenger/Chipollino/files/11078410/rendered_report.pdf)

Если кто-то хочет поучаствовать в написании статьи на SYRCoSE, пишем по почте. Поскольку вы соучастники Чиполлино, моя моральная обязанность вам это предложить.

**Comment by TonitaN** [comment]
Тестирование на примерах, сгенерированных вслепую, показывает, что по скорости+точности анализ регексов на базе Чиполлино (Ambiguity + трансмоноид) опережает всё из этого:

https://github.com/2bdenny/ReScue
https://github.com/NicolaasWeideman/RegexStaticAnalysis
https://github.com/cuhk-seclab/Revealer

Если честно, я сама в шоке (хотя над функцией Ambiguity очень знатно надругалась для получения такого результата). Остальные реализации из статей по ReDoS запустить не удалось - их документация не соответствует коду, или вообще код явно нерабочий. 

Ещё не поздно записаться в рабочую группу, кто желает =) Но это - последний день.

**Comment by TonitaN** [comment]
Вот небольшая демонстрация сравнительного анализа:
[out.pdf](https://github.com/StarikTenger/Chipollino/files/11132375/out.pdf)
Самый точный инструмент - RSA (использует статический анализ), остальные на случайном поиске, поэтому у них столько "безопасных" регулярок. Это неправда, правда - в первой колонке (и последней 😎). Параметры изменены так, чтобы максимально приблизить функциональности всех инструментов (я отключила в RSA поиск атак, чтобы не выжирали время). Регулярки сгенерированы вслепую человеком, который не видел Чиполлино и последнюю версию определения неоднозначности, в принципе 👀.

Кто-то не верил, что у проекта отличный потенциал к развитию? )
