### ISSUE TITLE
Напутствие и прощание

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#258]
С релизом я закрою эту тему.

Увы, похоже, жизнь распорядилась так, что мы с вами уже не увидимся в Переславле. Не так я представляла этот визит, даже надеялась, что релиз и презентацию можно будет отметить всем вместе. Но видимо, когда я поняла, что релизу быть, и что мы справились, "режим бога" сразу выключился... Что ж, это отличный показатель, насколько этот проект был мне важен, даже если я не слишком хотела это рефлексировать.
Продолжая сантименты, теперь мне страшно, что лучше, чем ваш поток, я уже никого не встречу. Хотелось бы верить, что вы - не лучшие, но боюсь, что статус "лучшей команды по тфя" за вами ещё подержится. И своим проектом вы оказали в 100500 раз более ценную услугу будущим поколениям, чем какими-то обменниками лаб и РК, которые в случае тфя ещё и не всегда так уж помогают 😈 Конечно же, я буду развивать его, как минимум в тех пределах, которые видны сейчас. Вряд ли больше - без "лучшей команды" уже не будет такого куража.

За @xendalm поболею дистанционно. Верю, что это не последний такой релиз, и не последнее ваше выступление (не в контексте тфя, а в общем). Так что если в первый раз будет не идеально, это даже хорошо, а то потом всё время придётся ориентироваться на уровень не ниже. Но надеюсь, что всё пройдёт так, как вы того заслужили.

@Robby-the-paladin , вряд ли у нас получится экзамен в воскресенье, но всё-таки постарайтесь допуститься, вдруг сильно повезёт. Однако всё же помним, что это моё дополнительное время, и стараемся слишком сильно не злоупотреблять, ок? Тогда, когда время было ваше, вас это не слишком заботило. @mathhyyn , можете считать, что я злонамеренно скрываю компромат на вас, потому что я поняла, что ваши контрольные в мгту и всё равно я не вспомню точно, что там было заготовлено "на сладкое" 😈 @xtoter , я обязательно узнаю у Коновалова, как там поживает ваш курсач, поскольку сейчас пришлось выкручиваться с `weight`-функцией для разбиения по длине. И давайте там становитесь должником-отличником, это гораздо интереснее, чем просто отличником или просто должником (хотя по факту оценки не важны, но так хотя бы забавно). @dak151449 , и до динамического рефала-5 когда-нибудь дойдёт очередь, вон кое-кто страдал, что его нет и приходится заниматься генерацией кода из плюсов. И передавайте привет моему соседу по плантации 🏝 Надо было и его взять, всех бы как-нибудь спать уместили 😂

P.S. - Забыла сказать спасибо @shevchenkokk (надеюсь добиться когда-нибудь того, что удастся подтвердить все те гипотезы) и @alina8031 , которой пришлось первой входить в тему генерации теха. А @StarikTenger ещё не закончил свою работу - кто-то же должен отревьюить 200 коммитов с рефалом, а кто, как не капитан?

P.P.S. - @xtoter , в тему курсовых про рефал - теперь я буду следить за вами :)

**Comment by TonitaN** [comment]
Дедлайнеры :( Дальше будет "до релиза -2 дня"?

**Comment by xtoter** [comment]
Будет!

**Comment by TonitaN** [comment]
Лучшее -- враг хорошего... Обнаружила психологический момент, что после нашего проекта стала сразу видеть излишний пиксель и некрасивые графвизовские шрифты в курсовых :)  Теперь всех придётся в dot2tex или ещё куда-нибудь отправлять, чтобы быть на уровне чиполлино.
