### ISSUE TITLE
Переписать минимизацию

### ISSUE THREAD

**Issue by StarikTenger** [StarikTenger/Chipollino#36]
Найти оптимальный алгоритм минимизации, а то *O(n^7)* это страшно

**Comment by TonitaN** [comment]
Наивный вопрос: это O(n^7) неужели при объединении эквивалентных состояний понадобилось? А разве нет смысла написать отдельную функцию, объединяющую состояния автомата по классам разбиения? Флаг детерминизма при этом можно просчитать в процессе, не обязательно делать дополнительный обход автомата.
@xendalm объединял бисимилярные состояния не в автомате, а в грамматике, из-за чего его алгоритм оказался не переносимым, но @dak151449 же делал подобное в IlieYu методе, правда, с НКА. Никак нельзя унифицировать несколько похожих операций в одну абстрактную?

**Comment by shevchenkokk** [comment]
#33
