### ISSUE TITLE
График проекта

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#4]
Капитану необходимо определить очерёдность выполнения подзадач у каждого из участников проекта. Например, строить эпсилон-замыкания состояний (подзадача для удаления эпсилон-правил) - это базовая задача, которая нужна многим. Объединять состояния по классам эквивалентности (на входе метода: автомат и множество подмножеств состояний, которые нужно объединить ) - скелетный метод, нужный всем. Производные - полезная вещь при проверке эквивалентности или вложения языков регулярок (строим альтернативу двух регулярок, строим её автомат Брзозовски, сравниваем с автоматами для исходных регулярок. Совпала с одним из двух - значит, вложение есть). А например, определение степени неоднозначности НКА - задача, от которой не зависит ничего, её можно задвинуть в низкоприоритетные.
Тайпчекера можно немедленно загрузить реализацией методов, которые понадобятся не только для динамической проверки типов: проверка на наличие ловушки, проверка на детерминированность и т.п.

**Comment by TonitaN** [comment]
Нулевая задача для дизайнера --- создать шаблон пустого документа и заголовок метода добавления описания шага (вычисления предиката, функции или процедуры `test`). 

Тестировщик может (и должен) начинать писать генератор тестов вообще независимо от всех, иначе, если генератор будет использовать те же методы, что и анализатор, некоторые ошибки окажутся замаскированы (например, всегда порождаются детерминированные автоматы с единственной ловушкой, потому что так устроена структура данных ДКА в проекте). Кстати, тестировщик - единственный, кому разрешается подключать к генератору модули на других языках, если это будет необходимо.

Тайпчекер уже сейчас должен продумывать, какие свойства алгебры автоматов он будет использовать. Даже если у вас ещё нет до конца оформленных структур данных, ТЗ уже должно быть.

Товарищ капитан, вы же наверняка пользуетесь какой-то системой менеджмента задач. Как раз она и нужна для поддержки графика проекта. Чтобы было понятно, что загружены уже точно все, не могли бы вы выложить скриншот с текущим распределением тасков?

**Comment by StarikTenger** [comment]
(почти) все задания распределены, участники нагружены. Скриншот с распределением прикладываю

![изображение](https://user-images.githubusercontent.com/48261272/195141273-db4d2ca9-8e76-457e-a88f-c33bca8d2725.png)

**Comment by TonitaN** [comment]
Всё замечательно, кроме того что дизайнер пока прохлаждается. Желательно загрузить созданием шаблона и даже уже реализацией логов к бисимуляции и эпсилон-замыканию как минимум (придумать, как отмечать в отрисовке графов эпсилон-замыкания состояний и факт бисимуляции состояний).

**Comment by TonitaN** [comment]
По промежуточному итогу, +2 @StarikTenger  за хорошую организацию групповой работы. Надеюсь, остальные, кто пока ещё не был слишком активен в проекте, проявятся в следующую неделю, и весь главный функционал будет сделан.

**Comment by TonitaN** [comment]
Кстати, @dak151449 точно тоже будет награждён бонусом, и не он один - в рамках раздачи бонусов по индивидуальным вариантам.

**Comment by TonitaN** [comment]
Уже давно не актуально, т.к. задачи другие.
