### ISSUE TITLE
Нормализация regex по пользовательским правилам переписывания.

### ISSUE THREAD

**Issue by xtoter** [StarikTenger/Chipollino#46]
![image](https://user-images.githubusercontent.com/76103754/197050381-12aa0357-9088-45a5-851d-3bf2a670f6ba.png)
![image](https://user-images.githubusercontent.com/76103754/197050452-f9c2730b-0d1b-476a-96b8-42602b60cece.png)
грустно

**Comment by xtoter** [comment]
#62

**Comment by xtoter** [comment]
https://www.youtube.com/watch?v=6S6BbxhAF8c

**Comment by TonitaN** [comment]
Как вызывать? Я переписала путь к правилам как просто "Rules.txt" и кладу их в папку исполняемого файла. Должно работать?
