### ISSUE TITLE
Структура конечного автомата

### ISSUE THREAD

**Issue by xendalm** [StarikTenger/Chipollino#5]

**Comment by xtoter** [comment]
Возможно нужно добавить поддержку алфавита для состояний (см скрины).
Пример
![image](https://user-images.githubusercontent.com/76103754/193479340-fba9bb12-a7e1-41af-85da-bd97c028ad28.png)
Текущий вывод
![image](https://user-images.githubusercontent.com/76103754/193479356-05692062-b45a-4231-b9b9-994d41aeef06.png)

**Comment by TonitaN** [comment]
Насколько я понимаю, для этих целей есть метка (типа строка). Немного больше усилий потребуется при работе с производными: если по производным строится автомат, то в процессе этого построения <<именами состояний>> автомата являются регулярки либо их множества (в случае конструкции Антимирова). Там придётся делать таблицы <<состояние - регулярка (множество регулярок)>>, и логгировать как имена состояний элементы этой таблицы.

**Comment by StarikTenger** [comment]
Класс сделан, ветка слита в `main`. Так что issue можно закрыть
