### ISSUE TITLE
Слияние по бисимуляции

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#65]
Беру вот такую регулярку: `(a|b)*b`. Строю автомат Глушкова, потом делаю слияние по бисимуляции. Почему-то итог содержит три состояния, два из которых бисимилярны (стартовое и состояние 2). Возможно, кое-кто не учёл, что слияние по бисимуляции должно сохранять финальность состояний, но не обязано сохранять их ко-финальность ("стартовость").

**Comment by xendalm** [comment]
Невнимательно читал презентацию, исправлю
