### ISSUE TITLE
It's a trap!

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#66]
При переводе в автомат Глушкова тривиальной регулярки `a*` и применении к результату метода `add_trap_state` получается автомат с двумя финальными состояниями (т.е. ловушка не добавляется, что в принципе адекватно ситуации, если алфавит изначально состоит только из `a`). Но при попытке применить к нему `remove_trap_state` получается вообще пустой автомат.

EDIT: `remove_trap_state` не только в этих случаях порождает пустой автомат, а даже когда ловушка есть, например, на `(aba)*a`.

Тестировщик, ау!

**Comment by shevchenkokk** [comment]
Порождается пустой автомат, потому что код внутри функции `remove_trap_state` на данный момент закомментирован ввиду доработки. Всё обязательно поправим.

**Comment by TonitaN** [comment]
Из-за отсутствия применения метода добавления ловушки, теряются элементы языка при применении метода `complement`.
