### ISSUE TITLE
Класс регулярных выражений

### ISSUE THREAD

**Issue by StarikTenger** [StarikTenger/Chipollino#7]

**Comment by Robby-the-paladin** [comment]
Имеет смысл писать рекурсивную реализацию regex, т.к. каждая подрегулярка является регуляркой, и в алгосах требуется возможность использовать функции регулярок от подргулярок. Такая реализация не мешает кешировать результаты вычислений, просто результаты функций будут вычисляться лениво.

**Comment by dak151449** [comment]
Вроде бы звучит логично

**Comment by xendalm** [comment]
А текущее использование структуры Term чем мотивированно?

**Comment by StarikTenger** [comment]
> А текущее использование структуры Term чем мотивированно?

Идея была в том, что в структуре **Regexp** содержится метаинформация, которая не нужна в термах. Например, указатель на язык

Но как отметил Эдгар, обращение к языку - операция ленивая, т.е. пока не понадобится, это поле остаётся пустым. Поэтому если оно будет и в подрегулярках, то как минимум мешать не будет

**Comment by StarikTenger** [comment]
Принятое решение: избавиться от класса `Term`, использовать Regex как `дерево`

**Comment by TonitaN** [comment]
@dak151449 , НКА загляденье! Вам зачёт.
