### ISSUE TITLE
Странное поведение determinize

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#83]
Странное поведение получается при последней детерминизации. Автомат из 15 состояний превращается в тривиальный с двумя:
```
R1 = to_glushkov(bbb*(aaa*bbb*)*|bb*|aa*|(ab)*)
R2 = determinize.reverse.determinize R1
```
Возможно, есть и минимальный тест, сейчас поищу.

**Comment by TonitaN** [comment]
В общем да, это всегда выстреливает после обращения. Я думаю, тут опять трапик вылез - после обращения он стал недостижимым и всё сломал.

**Comment by shevchenkokk** [comment]
Нашел тупейшую ошибку, которая заключалась в том, что поиск достижимых по eps-состояниям переходов изначально находился для нулевого состояния, а не для `initial_state`. В этом и была проблема.
Поправлю.

**Comment by TonitaN** [comment]
@mathhyyn 1-0)))
