### ISSUE TITLE
Бонус за командную работу

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#86]
После того как я посмотрю результат работы, я поставлю баллы по факту того, что увижу. Однако я увижу не всё - командную работу делали вы. Поэтому капитану даётся 3 балла, чтобы поощрить того, кто наиболее ответственно относился к работе и выручал команду, после того как все основные участники получат зачёты. Можете их разделить на кого-то двоих.

**Comment by TonitaN** [comment]
После багфикса распределение баллов будет такое:
- @StarikTenger 13 баллов (взял на себя часть работы тайпчекера)
- @shevchenkokk 11 баллов (за весь функционал)
- @xtoter 6 (за моноид)+6 (за переписывание)+4 (за Ардена)+2 (за язык) балла = 18 баллов, но учтите, я ещё нормально не могла потестировать ваши модули, т.к. они как-то криво подключены к интерпретатору, и баги ещё точно будут
- @Robby-the-paladin 11 баллов (за весь функционал)
- @xendalm ещё бонусные +2 балла, когда дотестирую меру неоднозначности
- @mathhyyn 9 баллов  (штраф -1 за почти не видимое тестирование, а если бы сделали генератор гипотез и протестировали, было бы 11). Шанс получить 10 баллов есть, если завтра проявите активность в тестировании.
- @alina8031 9 баллов (у вас была очень приятная и творческая задача, шанс нафармить много баллов, но увы, итоговый latex выглядит почти как блокнотный текст, поэтому штраф за просрочку не аннулирован).
- @SoFa325 8 баллов (затянули с тайпчекером, поэтому получаете штраф 2 балла, но если исправите баги до второго дедлайна, т.е. завтра, то получите 9 баллов, а не 8)

**Comment by TonitaN** [comment]
Поставила всем зачёт за групповую часть лабы (а некоторым ещё и за индивидуальную), и многим добавила баллов сверх указанных здесь - за продуктивную работу и багфикс. Сами всё увидите в ЭУ. Единственный, кто пока получил меньше обещанного - это @xtoter (11 баллов) - предстоит ещё серьёзный багфикс последнего модуля (нормализации), и Ардена пока не проверяла. Я вообще не уверена, что вы успеете сделать 3 лабораторную, с учётом всех этих фиксов, но у вас за одну будет как за две (правда, за две не то чтобы сильно с бонусами, поэтому можете и 3 лабу попробовать успеть сделать).
За `Ambiguity` бонус для @xendalm поставила авансом, но фикса всё равно жду. За `Semdet2` будет ещё 3 балла, но их пока не добавляла - там ещё тоже наверняка багфикс будет, с учётом сложностей с разметками.

**Comment by StarikTenger** [comment]
@TonitaN 
Мы определились с распределением:
@xtoter 2 балла
@alina8031 1 балл

**Comment by TonitaN** [comment]
Вот что за жизнь у @xendalm : сначала приходится торговаться, чтобы команде дали побольше баллов, а потом про эти баллы забывают :( Ну не надо так не надо, я насильно навязывать не буду.

**Comment by TonitaN** [comment]
А вот это не закрывается: с учётом (не)рабства, ещё 13 баллов есть.
