### ISSUE TITLE
nfa <- dfa typecheck

### ISSUE THREAD

**Issue by mathhyyn** [StarikTenger/Chipollino#88]
Тайпчекер не учитывает, что в функцию, которая принимает nfa на вход, может передаваться dfa

**Comment by StarikTenger** [comment]
Пример падения:
```
N1 = RemEps.RemEps.Annote.Annote.Antimirov a
```

**Comment by mathhyyn** [comment]
Аналогично с предикатами
N1 = Glushkov b*b
N2 = Glushkov bb*
N3 = Determinize N1
Equal N2 N3
