### ISSUE TITLE
Опять что-то странное с обращением

### ISSUE THREAD

**Issue by TonitaN** [StarikTenger/Chipollino#97]
Всё падает:
```
R1 = Glushkov bbb*(aaa*bbb*)*|bb*|aa*|(ab)* !!
R2 = Reverse.Determinize R1 !!
```
Без добавления последнего `Reverse` всё нормально.

**Comment by xendalm** [comment]
Сам `Reverse` работает без ошибок, видимо проблема на уровне интерпретатора

![image](https://user-images.githubusercontent.com/35781938/200163367-0f5f804d-5567-4346-a9d3-f6e4a1f13716.png)
![image](https://user-images.githubusercontent.com/35781938/200163409-274a9646-b63c-460b-be15-42ebe1e4410a.png)

**Comment by TonitaN** [comment]
А я вот вижу, что работает как-то странно. Пустое состояние не достижимо из стартового.

**Comment by shevchenkokk** [comment]
Но разве это не ловушка, которая получается при детерминизации? Или вы хотите, чтобы она удалялась при обращении по причине недостижимости из стартового?

**Comment by TonitaN** [comment]
Я вот не уверена, что все функции будут правильно обрабатывать случай, когда есть недостижимое состояние. Например, трансформационный моноид, или подсчёт количества состояний в автомате. Тем более что ловушка (единственная!) в трансформационном моноиде как бы всё равно присутствует (как отсутствие перехода по букве в классе эквивалентности), а ко-ловушка там всё сломает. И она превращает автомат в сильно недетерминированный даже на константной регулярке типа `abaa`, где все Глушковские алгоритмы сразу же порождают НКА без альтернативных переходов.

**Comment by TonitaN** [comment]
Вообще, с учётом того, что ловушка должна быть строго одна (неоткуда им взяться в нескольких экземплярах, кроме как от неаккуратного обращения с пересечением, дополнением и конкатенацией автоматов), я бы сказала страшное слово *рефакторинг* --- не имеет ли смысл выделить её в отдельный объект структуры NFA? Это сэкономило бы огромное число лишних проходов по состояниям автомата в тех случаях, когда наличие ловушки что-то меняет. Ну или как минимум `get_trap_state` метод нужен, и `is_trim` - всё равно так или иначе выгоднее иметь эту ловушку выделенным состоянием. 
Понятно, что в данный момент функции пересечения и объединения на самом деле являются не функциями пересечения и объединения *автоматов*, а являются таковыми для *языков* (т.к. не автоматы используют, а их детерминизированные версии), потому что используются при проверке свойств языков, но из-за неучёта ловушек и ко-ловушек объединение двух автоматов, тупо распознающих язык `{a}` (т.е. слово из одной буквы `a`) имеет 9(!!!) состояний. Это уже баг проектирования, как по мне.
